package com.ttbbank.oneapp.framework.element.android;

import com.ttbbank.oneapp.framework.FindBy;
import com.ttbbank.oneapp.framework.OneAppElement;
import com.ttbbank.oneapp.framework.OneAppElementKeys;

import java.util.Map;

public class LendingAndroidOneAppElements {
    private LendingAndroidOneAppElements() {

    }

    //Lending
    private static final  OneAppElement PIN_0_BUTTON_LENDING = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/key_00");
    private static final  OneAppElement PIN_1_BUTTON_LENDING = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/key_01");
    private static final  OneAppElement PIN_2_BUTTON_LENDING = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/key_02");
    private static final  OneAppElement PIN_3_BUTTON_LENDING = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/key_03");
    private static final OneAppElement LENDING_CASH_TRANSFER_PAYMENT_OPTION = new OneAppElement(FindBy.XPATH, "//*[text()='(Cash Transfer)']");
    private static final OneAppElement LENDING_CASH_FOR_YOU_BUTTON = new OneAppElement(FindBy.XPATH, "(//*[text()='Cash for You'])[1]");
    private static final OneAppElement LENDING_NEXT_CASH_FOR_YOU_BUTTON = new OneAppElement(FindBy.XPATH, "//*[text()='Next']");
    private static final OneAppElement LENDING_AMOUNT_CASH_FOR_YOU_INPUT = new OneAppElement(FindBy.CSS_SELECTOR, "#WORKING_INFO_OFFICE_NAME_input");
    private static final OneAppElement LENDING_CASH4YOU_CLICK_OUT = new OneAppElement(FindBy.XPATH,"//*[text()='Enter Amount to Transfer']");
    private static final OneAppElement LENDING_CASH_CHILL_CHILL_PAYMENT_OPTION = new OneAppElement(FindBy.XPATH,"//*[text()='Installment']");
    private static final OneAppElement LENDING_CASH_CHILL_SELECT_BOX_MONTH = new OneAppElement(FindBy.CSS_SELECTOR,"#selectBox");
    private static final OneAppElement LENDING_CASH_CHILL_SELECT_12_MONTH = new OneAppElement(FindBy.TEXT,"12 Month");
    private static final OneAppElement LENDING_CASH_CHILL_TIER_1_TO_10 = new OneAppElement(FindBy.XPATH,"//*[text()='Tier month 1-6']");
    private static final OneAppElement LENDING_CASH_CHILL_TIER_11_TO_CHOOSE = new OneAppElement(FindBy.XPATH,"//*[text()='Tier month 7-12']");
    private static final OneAppElement LENDING_CASH_CHILL_FEE_TIER_1 = new OneAppElement(FindBy.XPATH,"//*[text()='12.99%']");
    private static final OneAppElement LENDING_CASH_CHILL_FEE_TIER_2 = new OneAppElement(FindBy.XPATH,"//*[text()='22.00%']");
    private static final OneAppElement LENDING_CASH_CHILL_MORE_THAN_11_MONTH = new OneAppElement(FindBy.XPATH,"//*[text()='Interest will be calculated as a effective rate.']");
    private static final OneAppElement LENDING_CASH_CHILL_PAYMENT_SUMMARY = new OneAppElement(FindBy.XPATH,"//*[text()='Payment summary']");
    private static final OneAppElement LENDING_CASH_CHILL_TOTAL_PAYMENT = new OneAppElement(FindBy.XPATH,"//*[text()='Total payment']");
    private static final OneAppElement LENDING_CASH_CHILL_MONTHLY_PAYMENT = new OneAppElement(FindBy.XPATH,"//*[text()='Monthly payment']");
    private static final OneAppElement LENDING_CASH_CHILL_MONTH_INSTALLMENT = new OneAppElement(FindBy.XPATH,"//*[text()='No. of monthly installments']");
    private static final OneAppElement LENDING_CASH4YOU_CONFIRM_PAGE = new OneAppElement(FindBy.XPATH,"//*[text()='Confirm Cash for You']");
    private static final OneAppElement LENDING_CASH4YOU_CHECKED_BOX_CONFIRM = new OneAppElement(FindBy.XPATH,"//label[@id=\"1\"]");
    private static final OneAppElement LENDING_CASH4YOU_CONFIRM_BUTTON = new OneAppElement(FindBy.XPATH,"//*[text()='Confirm']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_TRANSFER_INFO = new OneAppElement(FindBy.XPATH,"//*[text()='Cash Transfer Information']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_CHILL_INFO = new OneAppElement(FindBy.XPATH,"//*[text()='Cash Chill Chill Information']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_SUCCESS_FROM = new OneAppElement(FindBy.XPATH,"//*[text()='From']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_SUCCESS_TO = new OneAppElement(FindBy.XPATH,"//*[text()='To']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_SUCCESS_AMOUNT = new OneAppElement(FindBy.XPATH,"//*[text()='Amount']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_SUCCESS_PAYMENT = new OneAppElement(FindBy.XPATH,"//*[text()='Payment plan']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_SUCCESS_FEE = new OneAppElement(FindBy.XPATH,"//*[text()='Fee']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_SUCCESS_VAT = new OneAppElement(FindBy.XPATH,"//*[text()='VAT']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_SUCCESS_ANNUAL = new OneAppElement(FindBy.XPATH,"//*[text()='Annual interest rate']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_SUCCESS_REF = new OneAppElement(FindBy.XPATH,"//*[text()='Reference No.']");
    private static final OneAppElement LENDING_CASH4YOU_CASH_ADVANCE_BACK_TO_MAIN = new OneAppElement(FindBy.XPATH,"//*[text()='Back to Main Page']");


    private static final OneAppElement LENDING_CREDIT_CARD_RESERVE = new OneAppElement(FindBy.TEXT, "4770-25XX-XXXX-0175");
//    private static final OneAppElement LENDING_APPLY_SO_GOOD_BUTTON = new OneAppElement(FindBy.RESOURCE_ID, "1");
    private static final OneAppElement LENDING_APPLY_SO_GOOD_BUTTON_SSC = new OneAppElement(FindBy.XPATH, "(//*[text()=\"so goood\"])[4]");
    private static final OneAppElement LENDING_NEXT_BUTTON_INSTALL_PLAN = new OneAppElement(FindBy.XPATH, "//*[text()=\"Next\"]");
    private static final OneAppElement LENDING_SELECT_ALL_TRANSACTION = new OneAppElement(FindBy.XPATH, "//*[text()=\"Select All\"]");
    private static final OneAppElement LENDING_SELECT_TRANSACTION_1 = new OneAppElement(FindBy.XPATH, "(//label[@id=\"cid\"])[2]");
    private static final OneAppElement LENDING_SELECT_TRANSACTION_2 = new OneAppElement(FindBy.XPATH, "(//label[@id=\"cid\"])[3]");
    private static final OneAppElement LENDING_NEXT_BUTTON_TRANSACTION = new OneAppElement(FindBy.XPATH, "//*[text()=\"Next\"]");
    private static final OneAppElement LENDING_SO_GOOD_SELECT_INSTALLMENT_PLAN = new OneAppElement(FindBy.XPATH,"//*[text()='Select Installment Plan']");
    private static final OneAppElement LENDING_SELECT_PLAN_3_MONTH = new OneAppElement(FindBy.XPATH,"//*[text()='0% 3 Months']");
    private static final OneAppElement LENDING_SELECT_PLAN_6_MONTH = new OneAppElement(FindBy.XPATH, "//*[text()='0% 6 Months']");
    private static final OneAppElement LENDING_SELECT_PLAN_10_MONTH = new OneAppElement(FindBy.XPATH, "//*[text()='0% 10 Months']");
    private static final OneAppElement LENDING_SO_GOOD_DETAIL_OF_INSTALLMENT_PLAN = new OneAppElement(FindBy.TEXT,"Detail of Installment Plan");
    private static final OneAppElement LENDING_DATA_TRANSACTION = new OneAppElement(FindBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View[2]/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.widget.Image");
    private static final OneAppElement LENDING_TERM_AND_CONDITION_DETAIL_INSTALLMENT = new OneAppElement(FindBy.TEXT, "I have read and agree to the terms and conditions.");
    private static final OneAppElement LENDING_SO_GOOD_CONFIRM_BTN = new OneAppElement(FindBy.TEXT,"Confirm");
    private static final OneAppElement LENDING_SO_GOOD_SUCCESFUL = new OneAppElement(FindBy.TEXT, "Successfully Applied so goood");
    private static final OneAppElement LENDING_BACK_TO_MAIN_PAGE_SO_GOOD = new OneAppElement(FindBy.TEXT, "Back to main page");
    private static final OneAppElement LENDIND_WORD_CREDIT_CARD_NO = new OneAppElement(FindBy.TEXT, "Credit number");
    private static final OneAppElement LENDING_WORD_SELECTED_TRANSACTION = new OneAppElement(FindBy.TEXT, "Number of transaction");
    private static final OneAppElement LENDING_WORD_TOTAL_INSTALLMENT = new OneAppElement(FindBy.TEXT, "Total installment amount");
    private static final OneAppElement LENDING_WORD_INSTALLMENT_PLAN = new OneAppElement(FindBy.TEXT, "Installment plan");
    private static final OneAppElement LENDING_WORD_TRANSACTION_DATE = new OneAppElement(FindBy.TEXT, "Transaction date");
    private static final OneAppElement LENDING_WORD_TRANSACTION_TIME = new OneAppElement(FindBy.TEXT, "Transaction time");
    private static final OneAppElement LENDING_MAIN_PAGE_UNBILLED = new OneAppElement(FindBy.RESOURCE_ID, "credit_landing_billed_list");
    private static final OneAppElement LENDING_GET_VALUE_TRANSACTION_1 = new OneAppElement(FindBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View[2]/android.view.View/android.view.View[2]/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View/android.widget.TextView[1]");
    private static final OneAppElement LENDING_GET_VALUE_TRANSACTION_2 = new OneAppElement(FindBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View[2]/android.view.View[1]/android.view.View[2]/android.view.View[2]/android.view.View[2]/android.view.View/android.widget.TextView");
    private static final OneAppElement LENDING_PARTIAL_SUCCESSFUL = new OneAppElement(FindBy.TEXT, "Partial successful");
//    private static final OneAppElement LENDING_MORE_BUTTON_LANDING_PAGE = new OneAppElement(FindBy.RESOURCE_ID, "credit_landing_more_id");
//    private static final OneAppElement LENDING_MORE_BUTTON_LANDING_PAGE = new OneAppElement(FindBy.TEXT, "More");
    private static final OneAppElement LENDING_MORE_BUTTON_LANDING_PAGE = new OneAppElement(FindBy.CSS_SELECTOR, "#credit_landing_more_id");
    private static final OneAppElement LENDING_CARD_DETAIL_MORE_BT_SUP_CARD = new OneAppElement(FindBy.XPATH,"(//*[@id=\"credit_landing_more_id\"])[4]");
    private static final OneAppElement LENDING_CARD_DETAIL_MORE_PRI_HAS_SUP = new OneAppElement(FindBy.XPATH,"(//*[@id=\"credit_landing_more_id\"])[3]");
    private static final OneAppElement LENDING_MORE_BUTTON_SSC_LANDING_PAGE = new OneAppElement(FindBy.XPATH, "//li[3]/div[@id=\"credit_landing_more_id\"]");
    private static final OneAppElement LENDING_PRODUCT_LANDING_CLOSE_MORE_BTN = new OneAppElement(FindBy.RESOURCE_ID,"btn-close");
    private static final OneAppElement LENDING_PRODUCT_LANDING_SWIPE_GRAY_WRAP = new OneAppElement(FindBy.TEXT,"grayWrap");
    private static final OneAppElement LENDING_PRODUCT_LANDING_BILLED_BTN = new OneAppElement(FindBy.RESOURCE_ID,"credit_landing_unbilled_list");
    private static final OneAppElement LENDING_PRODUCT_LANDING_UNBILLED_BTN = new OneAppElement(FindBy.RESOURCE_ID,"credit_landing_billed_list");
    private static final OneAppElement LENDING_PRODUCT_LANDING_SELECT_BOX = new OneAppElement(FindBy.RESOURCE_ID,"selectBox");
    private static final OneAppElement LENDING_PRODUCT_LANDING_SELECT_MONTH = new OneAppElement(FindBy.TEXT,"Jan 24");
    private static final OneAppElement LENDING_PRODUCT_LANDING_SPENDING = new OneAppElement(FindBy.TEXT,"Total spending this bill");
    private static final OneAppElement LENDING_CARD_DETAIL_BUTTON = new OneAppElement(FindBy.XPATH, "(//*[text()='Card Details'])[2]");
    private static final OneAppElement LENDING_CARD_DETAIL_ACCOUNT = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataLabel_1");
    private static final OneAppElement LENDING_CARD_DETAIL_POINT = new OneAppElement(FindBy.TEXT, "Points");
    private static final OneAppElement LENDING_PRODUCT_LANDIND_ACCOUNT = new OneAppElement(FindBy.RESOURCE_ID, "account-number");
    private static final OneAppElement LENDING_CARD_DETAIL_DATA_ACCOUNT = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataValue_2");
    private static final OneAppElement LENDING_CREDIT_CARD_SO_FAST = new OneAppElement(FindBy.TEXT, "so fast");
        private static final OneAppElement LENDING_CARD_DETAIL_SUP_CARD = new OneAppElement(FindBy.TEXT, "4050-16XX-XXXX-1119");
//    private static final OneAppElement LENDING_CARD_DETAIL_SUP_CARD = new OneAppElement(FindBy.TEXT, "4706-86XX-XXXX-0096");
    private static final OneAppElement LENDING_CARD_DETAIL_PRI_HAVE_SUP = new OneAppElement(FindBy.TEXT,"4770-63XX-XXXX-0095");
    private static final OneAppElement LENDING_CARD_DATAIL_DATA_CARD_NAME = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataValue_1");
    private static final OneAppElement LENDING_CARD_DETAIL_HEAD = new OneAppElement(FindBy.TEXT, "Card Detail");
    private static final OneAppElement LENDING_CARD_DETAIL_PRODUCT_NAME = new OneAppElement(FindBy.TEXT, "Product name");
    private static final OneAppElement LENDING_CARD_DETAIL_CARD_TYPE = new OneAppElement(FindBy.TEXT, "Card type");
    private static final OneAppElement LENDING_CARD_DETAIL_CARD_NUMBER = new OneAppElement(FindBy.TEXT, "Card number");
    private static final OneAppElement LENDING_CARD_DETAIL_CARD_HOLDER = new OneAppElement(FindBy.TEXT, "Card holder");
    private static final OneAppElement LENDING_CARD_DETAIL_CARD_LIMIT = new OneAppElement(FindBy.TEXT, "Card limit");
    private static final OneAppElement LENDING_CARD_DETAIL_TOTAL_AMOUNT_DUE = new OneAppElement(FindBy.TEXT, "Total amount due");
    private static final OneAppElement LENDING_CARD_DETAIL_MINIMUM = new OneAppElement(FindBy.TEXT, "Minimum amount due");
    private static final OneAppElement LENDING_CARD_DETAIL_STATEMENT = new OneAppElement(FindBy.TEXT, "Statement date");
    private static final OneAppElement LENDING_CARD_DETAIL_PAYMENT_DUE = new OneAppElement(FindBy.TEXT, "Payment due date");
    private static final OneAppElement LENDING_CARD_DETAIL_POINT_DETAIL = new OneAppElement(FindBy.TEXT,"Point Detail");
    private static final OneAppElement LENDING_CARD_DETAIL_OUTSTANDING = new OneAppElement(FindBy.TEXT,"Outstanding points");
    private static final OneAppElement LENDING_CARD_DETAIL_EXPIRING = new OneAppElement(FindBy.TEXT,"Expiring points");

    private static final OneAppElement LENDING_APPLY_STATEMENT_BUTTON = new OneAppElement(FindBy.TEXT,"Apply eStatement");
    private static final OneAppElement LENDING_FLASH_CARD_APPLY_ESTATEMENT_BT = new OneAppElement(FindBy.XPATH,"//*[@id=\"4\"]");
//    private static final OneAppElement LENDING_LOAN_APPLY_STATEMENT_BUTTON = new OneAppElement(FindBy.RESOURCE_ID,"shortcut-icon-1-1");
    private static final OneAppElement LENDING_LOAN_APPLY_STATEMENT_BUTTON = new OneAppElement(FindBy.XPATH,"//*[@id=\"main-shortcut-icon-1-1\"]");
    private static final OneAppElement LENDING_LOAN_HEADER_PAGE = new OneAppElement(FindBy.RESOURCE_ID,"landing-page-back-button-title");
    private static final OneAppElement LENDING_APPLY_ESTATEMENT_TERM_CONDITION = new OneAppElement(FindBy.TEXT,"I have read and agree to the terms and conditions");
    private static final OneAppElement LENDING_APPLY_ESTATEMENT_CONFIRM = new OneAppElement(FindBy.XPATH,"(//button[text()='Confirm'])[1]");
    private static final OneAppElement LENDING_APPLY_ESTATEMENT_VERIFY_DES = new OneAppElement(FindBy.RESOURCE_ID,"primary_desc");
    private static final OneAppElement LENDING_APPLY_ESTATEMENT_CONDITION = new OneAppElement(FindBy.XPATH,"//*[text()='I have read and agree to the terms and conditions.']");
    private static final OneAppElement LENDING_APPLY_FLASH_CARD_SELECTED_ACCOUNT = new OneAppElement(FindBy.TEXT,"4891-76XX-XXXX-0176");

    private static final OneAppElement LENDING_APPLY_ESTATEMENT_CONFIRM2 = new OneAppElement(FindBy.RESOURCE_ID,"verify-confirm-button");
    private static final OneAppElement LENDING_ESTATEMENT_MANAGE_EMAIL = new OneAppElement(FindBy.RESOURCE_ID,"informative_desc");
    private static final OneAppElement LENDING_ESTATEMENT_MANAGE_MAIL_HEADER = new OneAppElement(FindBy.TEXT,"Manage Email");
    private static final OneAppElement LENDING_ESTATEMENT_MANAGE_MAIL_NEXT = new OneAppElement(FindBy.RESOURCE_ID,"button_submit_change_email");
    private static final OneAppElement LENDING_ESTATEMENT_MANAGE_MAIL_ERROR = new OneAppElement(FindBy.RESOURCE_ID,"SETTING_MANAGE_EMAIL_INPUT_helptext");
    private static final OneAppElement LENDING_ESTATEMENT_MANAGE_MAIL_CLEAR = new OneAppElement(FindBy.RESOURCE_ID,"MANAGE_EMAIL_CLEAR_INPUT_BUTTON");
    private static final OneAppElement LENDING_ESTATEMENT_MANAGE_MAIL_INPUT = new OneAppElement(FindBy.RESOURCE_ID,"SETTING_MANAGE_EMAIL_INPUT_input");
    private static final OneAppElement LENDING_ESTATEMENT_MANAGE_MAIL_OTP_1 = new OneAppElement(FindBy.XPATH,"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View[2]/android.view.View/android.view.View[2]/android.view.View[2]/android.widget.EditText[1]");
    private static final OneAppElement LENDING_ESTATEMENT_VERIFY_EMAIL_SUCCESS_BUTTON = new OneAppElement(FindBy.RESOURCE_ID,"button_manage_email_success_confirm");
    private static final OneAppElement LENDING_ESTATEMENT_VERIFY_EMAIL_SUCCESS_TITLE = new OneAppElement(FindBy.RESOURCE_ID,"title_success");
    private static final OneAppElement LENDING_ESTATEMENT_VERIFY_EMAIL_SUCCESS_MESSAGE = new OneAppElement(FindBy.RESOURCE_ID,"message_success");
//    private static final OneAppElement LENDING_ESTATEMENT_CHANGE_EMAIL_BUTTON = new OneAppElement(FindBy.TEXT,"Change Email");
    private static final OneAppElement LENDING_ESTATEMENT_CHANGE_EMAIL_BUTTON = new OneAppElement(FindBy.XPATH,"//*[@id=\"__next\"]/div[1]/div[1]/div[4]/div/div[2]");
    private static final OneAppElement LENDING_ESTATEMENT_CONFIRM_TO_CHANGE_EMAIL = new OneAppElement(FindBy.RESOURCE_ID,"confirm-button-statement");
    private static final OneAppElement LENDING_ESTATEMENT_CONFIRM_TO_CHANGE_EMAIL2 = new OneAppElement(FindBy.XPATH,"//*[@id=\"confirm-button-statement\"]");

    private static final OneAppElement LENDING_REGISTER_TTB = new OneAppElement(FindBy.ID,"com.ttbbank.oneapp.uat:id/imageViewProfile");
    private static final OneAppElement LENDING_REGIS_BUTTON = new OneAppElement(FindBy.ID,"com.ttbbank.oneapp.uat:id/full_width_primary_btn");
    private static final OneAppElement REGISTER_ACCEPT_CONDITION = new OneAppElement(FindBy.ID,"com.ttbbank.oneapp.uat:id/terms_and_conditions_checkbox");
    private static final OneAppElement REGISTER_NEXT_BUTTON = new OneAppElement(FindBy.ID,"com.ttbbank.oneapp.uat:id/terms_and_conditions_next_btn");
    private static final OneAppElement REGISTER_CITIZEN_ID = new OneAppElement(FindBy.ID,"com.ttbbank.oneapp.uat:id/edt_component");
    private static final OneAppElement REGISTER_NEXT_BUTTON_CITIZEN = new OneAppElement(FindBy.ID,"com.ttbbank.oneapp.uat:id/next_btn");
    private static final OneAppElement REGISTER_OTP = new OneAppElement(FindBy.ID,"com.ttbbank.oneapp.uat:id/layout_otp_input");
    private static final OneAppElement REGISTER_IMAGE = new OneAppElement(FindBy.ID,"com.ttbbank.oneapp.uat:id/img_citizen_id_card");
    private static final OneAppElement REGISTER_NEXT_COMPLETE = new OneAppElement(FindBy.ID,"com.ttbbank.oneapp.uat:id/complete_next_text");

    private static final OneAppElement LENDING_ALREADY_APPLY_ESTATEMENT = new OneAppElement(FindBy.XPATH,"//*[text()='Successfully Applied eStatement']");
    private static final OneAppElement LENDING_ALREADY_APPLY_TEXT = new OneAppElement(FindBy.XPATH,"//*[text()='eStatement will be sent to your email, starting from next billing cycle.']");
    private static final OneAppElement LENDING_BACK_TO_MAIN_PAGE_STATEMENT = new OneAppElement(FindBy.XPATH,"//*[@id=\"activation-complete-screen-btn\"]");
    private static final OneAppElement LENDING_ESTATEMENT_FINISH_PRODUCT = new OneAppElement(FindBy.RESOURCE_ID,"ColumnDataLabel_idLabel");
    private static final OneAppElement LENDING_ESTATEMENT_FINISH_TYPE = new OneAppElement(FindBy.RESOURCE_ID,"ColumnDataValue_idLabel");
    private static final OneAppElement LENDING_ESTATEMENT_FINISH_EMAIL = new OneAppElement(FindBy.RESOURCE_ID,"ColumnDataLabel_idLabel1");

    private static final OneAppElement LENDING_CLICK_CARD_LOAN_B_PLUS = new OneAppElement(FindBy.TEXT,"001-5-61080-1");
    private static final OneAppElement LENDING_LOAN_PAY_BILL_MENU = new OneAppElement(FindBy.TEXT,"Pay Bill");
    private static final OneAppElement LENDING_LOAN_PAID_TEXT = new OneAppElement(FindBy.TEXT,"Paid");
    private static final OneAppElement LENDING_LOAN_OUT_STANDING_TEXT = new OneAppElement(FindBy.TEXT,"Outstanding");
    private static final OneAppElement LOAN_HOME_SCREEN_BUTTON = new OneAppElement(FindBy.TEXT, "Loan");

    private static final OneAppElement LENDING_CLICK_CARD_LOAN_C2G = new OneAppElement(FindBy.TEXT,"003-5-71665-3");
    private static final OneAppElement LENDING_CLICK_CARD_HOME_LOAN = new OneAppElement(FindBy.TEXT,"001-5-13362-2");
    private static final OneAppElement LENDING_LOAN_ESTATEMENT_MENU = new OneAppElement(FindBy.TEXT,"Apply estatement");
    private static final OneAppElement LENDING_LOAN_TOP_UP_MENU = new OneAppElement(FindBy.TEXT,"Top up");
    private static final OneAppElement LENDING_LOAN_BOTTOM_SHEET_HEADER = new OneAppElement(FindBy.RESOURCE_ID,"bottom-sheet-header");
    private static final OneAppElement LENDING_LOAN_DETAIL_ACCOUNT_NUMBER = new OneAppElement(FindBy.TEXT,"Loan account number");
    private static final OneAppElement LENDING_LOAN_DETAIL_LOAN_SUFFIX = new OneAppElement(FindBy.TEXT,"Loan suffix");
    private static final OneAppElement LENDING_LOAN_DETAIL_ACCOUNT_NAME = new OneAppElement(FindBy.TEXT,"Account name");
    private static final OneAppElement LENDING_LOAN_DETAIL_MONTHLY_PAYMENT = new OneAppElement(FindBy.TEXT,"Monthly payment");
    private static final OneAppElement LENDING_LOAN_DETAIL_DUE_DATE = new OneAppElement(FindBy.TEXT,"Due date");
    private static final OneAppElement LENDING_LOAN_DETAIL_INTEREST = new OneAppElement(FindBy.TEXT,"Interest rate (per year)");
    private static final OneAppElement LENDING_LOAN_DETAIL_TENORS = new OneAppElement(FindBy.TEXT,"Tenors");
    private static final OneAppElement LENDING_LOAN_DETAIL_START_DATE = new OneAppElement(FindBy.TEXT,"Contract start date");
    private static final OneAppElement LENDING_LOAN_DETAIL_EXPIRY_DATE = new OneAppElement(FindBy.TEXT,"Contract expiry date");
    private static final OneAppElement LENDING_LOAN_DETAIL_REMARK = new OneAppElement(FindBy.TEXT,"Remark: for loan account closure, please contact 1428.");
    private static final OneAppElement LENDING_LOAN_DETAIL_PAYMENT = new OneAppElement(FindBy.TEXT,"Payment details will be shown on the next day if you pay via other methods");
    private static final OneAppElement LENDING_LOAN_PAYMENT_HISTORY = new OneAppElement(FindBy.TEXT,"Payment History");
    private static final OneAppElement LENDING_TRY_AGAIN_ACCOUNT_SUMMARY = new OneAppElement(FindBy.RESOURCE_ID,"com.ttbbank.oneapp.vit:id/button_try_again");
    private static final OneAppElement LENDING_SET_ATM_PIN_SELECT_ACCOUNT = new OneAppElement(FindBy.TEXT,"4706-80XX-XXXX-0894");
    private static final OneAppElement LENDING_SET_ATM_PIM_PRIMARY_MORE_MENU = new OneAppElement(FindBy.XPATH,"(//*[@id=\"credit_landing_more_id\"])[1]");
    private static final OneAppElement LENDING_SET_ATM_PIN_SELECT_SSC = new OneAppElement(FindBy.TEXT,"4706-86XX-XXXX-0146");
    private static final OneAppElement LENDING_SET_ATM_SSC_MORE_BUTTON = new OneAppElement(FindBy.XPATH,"(//*[@id=\"credit_landing_more_id\"])[2]");
    private static final OneAppElement LENDING_SET_ATM_PIN_MENU_BUTTON = new OneAppElement(FindBy.XPATH,"//*[text()='Set Card PIN']");
    private static final OneAppElement LENDING_SET_ATM_PIN_PAGE = new OneAppElement(FindBy.CSS_SELECTOR,"#enter-cvv-screen-header-label");
    private static final OneAppElement LENDING_SET_ATM_PIN_INFO_LABEL = new OneAppElement(FindBy.CSS_SELECTOR,"#enter-cvv-screen-info-label");
    private static final OneAppElement LENDING_SET_ATM_PIN_ENTER_PIN = new OneAppElement(FindBy.CSS_SELECTOR,"#PIN1");
    private static final OneAppElement LENDING_SET_ATM_PIN_ENTER_PIN2 = new OneAppElement(FindBy.CSS_SELECTOR,"#PIN2");
    private static final OneAppElement LENDING_SET_ATM_PIN_ERROR = new OneAppElement(FindBy.XPATH,"//*[text()='PIN does not match, please try again.']");
    private static final OneAppElement LENDING_SET_ATM_PIN_COMPLETE = new OneAppElement(FindBy.XPATH,"//*[text()='Successfully Set Card PIN']");
    private static final OneAppElement LENDING_SET_ATM_PIN_CARD_NUMBER = new OneAppElement(FindBy.XPATH,"//*[text()='Card number']");
    private static final OneAppElement LENDING_SET_ATM_PIN_CHANGED = new OneAppElement(FindBy.XPATH,"//*[text()='PIN has been changed.']");
    private static final OneAppElement LENDING_SET_ATM_PIN_BACK_TO_MAIN = new OneAppElement(FindBy.XPATH,"//*[text()='Back to Main Page']");


    private static final OneAppElement LENDING_SELECT_SCC_CARD_ACCOUNT = new OneAppElement(FindBy.TEXT,"4762-81XX-XXXX-0448");
    private static final OneAppElement LENDING_CARD_DETAIL_CARD_MANAGEMENT = new OneAppElement(FindBy.TEXT,"Card Management");
    private static final OneAppElement LENDING_CARD_DETAIL_ADJUST = new OneAppElement(FindBy.RESOURCE_ID,"id1");
    private static final OneAppElement LENDING_CARD_DETAIL_BLOCK_CARD = new OneAppElement(FindBy.RESOURCE_ID,"id2");
//    private static final OneAppElement LENDING_ADJUST_LIMIT_BUTTON = new OneAppElement(FindBy.TEXT,"Adjust Usage Limit");
    private static final OneAppElement LENDING_SET_LIMIT_SUP_CARD_SELECTED = new OneAppElement(FindBy.TEXT,"4706-86XX-XXXX-0096");
    private static final OneAppElement LENDING_SETLIMIT_SUP_MORE_BT_SUP_CARD = new OneAppElement(FindBy.XPATH,"(//*[@id=\"credit_landing_more_id\"])[2]");
    private static final OneAppElement LENDING_SET_LIMIT_PERMANENT_SELECT_CARD = new OneAppElement(FindBy.TEXT,"4762-81XX-XXXX-1992");
    private static final OneAppElement LENDING_SET_LIMIT_PERMANENT_PRIMARY_MORE_MENU = new OneAppElement(FindBy.XPATH,"(//*[@id=\"credit_landing_more_id\"])[1]");
    private static final OneAppElement LENDING_ADJUST_LIMIT_BUTTON = new OneAppElement(FindBy.XPATH,"//*[text()='Adjust Usage Limit']");
    private static final OneAppElement LENDING_ADJUST_LIMIT_INPUT_FIELD = new OneAppElement(FindBy.XPATH,"//*[@id=\"change-card-screen-input-field\"]");
    private static final OneAppElement LENDING_ADJUST_LIMIT_HEADER = new OneAppElement(FindBy.XPATH,"//*[text()=\"Adjust Usage Limit\"]");
    private static final OneAppElement LENDING_ADJUST_LIMIT_ERROR_LESS_THAN = new OneAppElement(FindBy.XPATH,"//*[text()=\"Usage limit cannot be less than outstanding balance or minimum credit limit.\"]");
    private static final OneAppElement LENDING_ADJUST_LIMIT_ERROR_MORE_THAN = new OneAppElement(FindBy.XPATH,"//*[text()='Usage limit cannot exceed maximum card limit.']");
    private static final OneAppElement LENDING_ADJUST_LIMIT_ERROR_EQUAL = new OneAppElement(FindBy.XPATH,"//*[text()='You have not adjusted the usage limit.']");
    private static final OneAppElement LENDING_ADJUST_LIMIT_MESSAGE_TEMP = new OneAppElement(FindBy.TEXT,"This is a temporary limit as it exceeds your card limit.");
    private static final OneAppElement LENDING_ADJUST_LIMIT_NEW_LIMIT = new OneAppElement(FindBy.CSS_SELECTOR,"#change-card-screen-new-available-limit");
//    private static final OneAppElement LENDING_ADJUST_LIMIT_NEXT_BUTTON = new OneAppElement(FindBy.RESOURCE_ID,"change-card-screen-next-button");
private static final OneAppElement LENDING_ADJUST_LIMIT_NEXT_BUTTON = new OneAppElement(FindBy.XPATH,"//*[text()='Next']");
    private static final OneAppElement LENDING_SET_TEMPORARY_LIMIT_SELECT_BOX = new OneAppElement(FindBy.RESOURCE_ID,"selectBox");
    private static final OneAppElement LENDING_SET_TEMPORARY_LIMIT_EDUCATION = new OneAppElement(FindBy.TEXT,"For education");
    private static final OneAppElement LENDING_SET_TEMPORARY_EXPIRY_DATE = new OneAppElement(FindBy.RESOURCE_ID,"test-id");
    private static final OneAppElement LENDING_SET_TEMPORARY_SELECTED_DATE = new OneAppElement(FindBy.ACCESSIBILITY_ID,"10 February 2022");
    private static final OneAppElement LENDING_SET_TEMPORARY_CLICK_SET = new OneAppElement(FindBy.RESOURCE_ID,"android:id/button1");
    private static final OneAppElement LENDING_SET_TEMPORARY_SUCCESSFULLY = new OneAppElement(FindBy.TEXT,"Successfully Adjusted Usage Limit");
    private static final OneAppElement LENDING_SET_TEMPORARY_INFO_SUCCESS = new OneAppElement(FindBy.TEXT,"Summary of card limit changes");
    private static final OneAppElement LENDING_ADJUST_LIMIT_TEXT_CONFIRM_LIMIT = new OneAppElement(FindBy.XPATH,"//*[text()='Confirm to Adjust Usage Limit']");
    private static final OneAppElement LENDING_ADJUST_LIMIT_CONFIRM_BUTTON = new OneAppElement(FindBy.XPATH,"//*[text()='Confirm']");
    private static final OneAppElement LENDING_ADJUST_LIMIT_COMPLETE = new OneAppElement(FindBy.XPATH,"//*[text()='Successfully Adjusted Usage Limit']");
    private static final OneAppElement LENDING_ADJUST_LIMIT_DETAIL_INFO = new OneAppElement(FindBy.XPATH,"//*[text()='Summary of card limit changes']");
    private static final OneAppElement LENDING_ADJUST_LIMIT_NEW_CREDIT = new OneAppElement(FindBy.XPATH,"//*[@id=\"ColumnDataLabel_1\"]");
    private static final OneAppElement LENDING_ADJUST_LIMIT_EFFECTIVE_DATE = new OneAppElement(FindBy.XPATH,"//*[@id=\"ColumnDataLabel_2\"]");
    private static final OneAppElement LENDING_ADJUST_LIMIT_TEMP_EXPIRY_DATE = new OneAppElement(FindBy.RESOURCE_ID,"ColumnDataLabel_3");
    private static final OneAppElement LENDING_ADJUST_LIMIT_BACK_TO_MAIN_PAGE = new OneAppElement(FindBy.XPATH,"//*[text()='Back to Main Page']");
    private static final OneAppElement LENDING_ACTIVATE_CREDIT_CARD_SELECT = new OneAppElement(FindBy.TEXT,"4891-76XX-XXXX-0549");
    private static final OneAppElement LENDING_ACTIVATE_SSC_CARD_SELECTED = new OneAppElement(FindBy.TEXT,"4770-25XX-XXXX-0175");
    private static final OneAppElement LENDING_ACTIVATE_CARD_PRIMARY_ENTER_CARD_NUMBER = new OneAppElement(FindBy.TEXT,"aria-label-button");
    private static final OneAppElement LENDING_ACTIVATE_CARD_HEADER = new OneAppElement(FindBy.TEXT,"Activate Card");
    private static final OneAppElement LENDING_ACTIVATE_ENTER_NUMBER_PIN0 = new OneAppElement(FindBy.RESOURCE_ID,"PIN0");
    private static final OneAppElement LENDING_ACTIVATE_ENTER_NUMBER_PIN1 = new OneAppElement(FindBy.RESOURCE_ID,"PIN1");
    private static final OneAppElement LENDING_ACTIVATE_ENTER_NUMBER_PIN2 = new OneAppElement(FindBy.RESOURCE_ID,"PIN2");
    private static final OneAppElement LENDING_ACTIVATE_ENTER_NUMBER_PIN3 = new OneAppElement(FindBy.RESOURCE_ID,"PIN3");
    private static final OneAppElement LENDING_ACTIVATE_ENTER_NUMBER_PIN5 = new OneAppElement(FindBy.RESOURCE_ID,"PIN5");
    private static final OneAppElement LENDING_ACTIVATE_ENTER_NUMBER_PIN6 = new OneAppElement(FindBy.RESOURCE_ID,"PIN6");
    private static final OneAppElement LENDING_ACTIVATE_ENTER_NUMBER_PIN7 = new OneAppElement(FindBy.RESOURCE_ID,"PIN7");
    private static final OneAppElement LENDING_ACTIVATE_ENTER_NUMBER_PIN8 = new OneAppElement(FindBy.RESOURCE_ID,"PIN8");
    private static final OneAppElement LENDING_ACTIVATE_CARD_ERROR_ENTER_CARD_NUMBER = new OneAppElement(FindBy.TEXT,"Incorrect card number, please try again.");
    private static final OneAppElement LENDING_ACTIVATE_CARD_ERROR_ENTER_CVV = new OneAppElement(FindBy.TEXT,"Incorrect CVV, please try again.");
    private static final OneAppElement LENDING_ACTIVATE_CARD_SUCCESSFULLY = new OneAppElement(FindBy.TEXT,"Successfully Activated Card");
    private static final OneAppElement LENDING_ACTIVATE_CARD_TEXT_CARD_NUMBER = new OneAppElement(FindBy.TEXT,"Card number");
    private static final OneAppElement LENDING_ACTIVATE_CARD_TEXT_CAN_USE = new OneAppElement(FindBy.TEXT,"You can now use this card.");
    private static final OneAppElement LENDING_ACTIVATE_CARD_COMPLETE_BUTTON = new OneAppElement(FindBy.RESOURCE_ID,"activation-complete-screen-btn");
    private static final OneAppElement LENDING_BLOCK_CARD_SELECT_ACCOUNT = new OneAppElement(FindBy.TEXT,"4762-81XX-XXXX-0083");
//    private static final OneAppElement LENDING_BLOCK_CARD_MENU_BUTTON = new OneAppElement(FindBy.TEXT,"Block card");
private static final OneAppElement LENDING_BLOCK_CARD_MENU_BUTTON = new OneAppElement(FindBy.XPATH,"//*[text()='Block Card']");
    private static final OneAppElement LENDING_BLOCK_CARD_PAGE_HEADER = new OneAppElement(FindBy.XPATH,"//*[@id=\"ENTER_CVV_SCREEN_HEADER_LABEL\"]");
    private static final OneAppElement LENDING_BLOCK_CARD_PAGE_CONFIRM = new OneAppElement(FindBy.XPATH,"//*[text()='Confirm']");
    private static final OneAppElement LENDING_BLOCK_CARD_SUCCESSFULLY = new OneAppElement(FindBy.TEXT,"Successfully Blocked Card");
    private static final OneAppElement LENDING_BLOCK_CARD_INFO_1 = new OneAppElement(FindBy.TEXT,"is already blocked.");
    private static final OneAppElement LENDING_BLOCK_CARD_INFO_2 = new OneAppElement(FindBy.TEXT,"New credit card will be sent");
    private static final OneAppElement LENDING_BLOCK_CARD_INFO_3 = new OneAppElement(FindBy.TEXT,"to your billing address.");
    private static final OneAppElement LENDING_BLOCK_CARD_DATE = new OneAppElement(FindBy.TEXT,"Transaction date");
    private static final OneAppElement LENDING_BLOCK_CARD_TIME = new OneAppElement(FindBy.TEXT,"Transaction time");
    private static final OneAppElement LENDING_CASH_TRANSFER_FLASH_SELECT_ACCOUNT = new OneAppElement(FindBy.TEXT,"4891-76XX-XXXX-0176");
    private static final OneAppElement LENDING_CASH_TRANSFER_CREDIT_SELECT_ACCOUNT = new OneAppElement(FindBy.TEXT,"4706-86XX-XXXX-0070");
    private static final OneAppElement LENDING_CASH_ADVANCE_SELECT_ACCOUNT = new OneAppElement(FindBy.TEXT,"4308-40XX-XXXX-0136");
    private static final OneAppElement LENDING_PRODUCT_LANDING_PRIMARY_ACCOUNT = new OneAppElement(FindBy.TEXT,"4706-80XX-XXXX-0894");
    private static final OneAppElement LENDING_PRODUCT_LANDING_SSC_ACCOUNT = new OneAppElement(FindBy.TEXT,"4770-25XX-XXXX-0175");

    private static final OneAppElement LENDING_FLEXI_LOAN_APPLY_BUTTON = new OneAppElement(FindBy.RESOURCE_ID,"cs_service_tab_apply_label_id");
    private static final OneAppElement LENDING_FLEXI_LOAN_CREDIT_CARD_MENU = new OneAppElement(FindBy.RESOURCE_ID,"cs_apply_card_label_id");
    private static final OneAppElement LENDING_FLEXI_LOAN_SELECTED_SO_SMART = new OneAppElement(FindBy.TEXT,"ttb so smart");
    private static final OneAppElement LENDING_FLEXI_LOAN_APPLY_CREDIT = new OneAppElement(FindBy.TEXT,"สมัครบัตรเครดิต");





    public static void init(Map<String, OneAppElement> oneAppElementHashMap) {
        //Lending

        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_FOR_YOU_BUTTON, LENDING_CASH_FOR_YOU_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_NEXT_CASH_FOR_YOU_BUTTON, LENDING_NEXT_CASH_FOR_YOU_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_AMOUNT_CASH_FOR_YOU_INPUT, LENDING_AMOUNT_CASH_FOR_YOU_INPUT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_TRANSFER_PAYMENT_OPTION, LENDING_CASH_TRANSFER_PAYMENT_OPTION);
        //Lending

        oneAppElementHashMap.put(OneAppElementKeys.PIN_0_BUTTON_LENDING, PIN_0_BUTTON_LENDING);
        oneAppElementHashMap.put(OneAppElementKeys.PIN_1_BUTTON_LENDING, PIN_1_BUTTON_LENDING);
        oneAppElementHashMap.put(OneAppElementKeys.PIN_2_BUTTON_LENDING, PIN_2_BUTTON_LENDING);
        oneAppElementHashMap.put(OneAppElementKeys.PIN_3_BUTTON_LENDING, PIN_3_BUTTON_LENDING);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_FOR_YOU_BUTTON, LENDING_CASH_FOR_YOU_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_NEXT_CASH_FOR_YOU_BUTTON, LENDING_NEXT_CASH_FOR_YOU_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_AMOUNT_CASH_FOR_YOU_INPUT, LENDING_AMOUNT_CASH_FOR_YOU_INPUT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CLICK_OUT,LENDING_CASH4YOU_CLICK_OUT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_TRANSFER_PAYMENT_OPTION, LENDING_CASH_TRANSFER_PAYMENT_OPTION);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_CHILL_PAYMENT_OPTION,LENDING_CASH_CHILL_CHILL_PAYMENT_OPTION);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_SELECT_BOX_MONTH,LENDING_CASH_CHILL_SELECT_BOX_MONTH);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_SELECT_12_MONTH,LENDING_CASH_CHILL_SELECT_12_MONTH);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_TIER_1_TO_10,LENDING_CASH_CHILL_TIER_1_TO_10);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_TIER_11_TO_CHOOSE,LENDING_CASH_CHILL_TIER_11_TO_CHOOSE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_FEE_TIER_1,LENDING_CASH_CHILL_FEE_TIER_1);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_FEE_TIER_2,LENDING_CASH_CHILL_FEE_TIER_2);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_MORE_THAN_11_MONTH,LENDING_CASH_CHILL_MORE_THAN_11_MONTH);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_PAYMENT_SUMMARY,LENDING_CASH_CHILL_PAYMENT_SUMMARY);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_TOTAL_PAYMENT,LENDING_CASH_CHILL_TOTAL_PAYMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_MONTHLY_PAYMENT,LENDING_CASH_CHILL_MONTHLY_PAYMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_CHILL_MONTH_INSTALLMENT,LENDING_CASH_CHILL_MONTH_INSTALLMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CONFIRM_PAGE,LENDING_CASH4YOU_CONFIRM_PAGE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CHECKED_BOX_CONFIRM,LENDING_CASH4YOU_CHECKED_BOX_CONFIRM);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CONFIRM_BUTTON,LENDING_CASH4YOU_CONFIRM_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_TRANSFER_INFO,LENDING_CASH4YOU_CASH_TRANSFER_INFO);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_CHILL_INFO,LENDING_CASH4YOU_CASH_CHILL_INFO);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_SUCCESS_FROM,LENDING_CASH4YOU_CASH_SUCCESS_FROM);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_SUCCESS_TO,LENDING_CASH4YOU_CASH_SUCCESS_TO);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_SUCCESS_AMOUNT,LENDING_CASH4YOU_CASH_SUCCESS_AMOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_SUCCESS_PAYMENT,LENDING_CASH4YOU_CASH_SUCCESS_PAYMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_SUCCESS_VAT,LENDING_CASH4YOU_CASH_SUCCESS_VAT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_SUCCESS_FEE,LENDING_CASH4YOU_CASH_SUCCESS_FEE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_SUCCESS_ANNUAL,LENDING_CASH4YOU_CASH_SUCCESS_ANNUAL);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_SUCCESS_REF,LENDING_CASH4YOU_CASH_SUCCESS_REF);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH4YOU_CASH_ADVANCE_BACK_TO_MAIN,LENDING_CASH4YOU_CASH_ADVANCE_BACK_TO_MAIN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CREDIT_CARD_RESERVE, LENDING_CREDIT_CARD_RESERVE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_APPLY_SO_GOOD_BUTTON_SSC, LENDING_APPLY_SO_GOOD_BUTTON_SSC);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_NEXT_BUTTON_INSTALL_PLAN, LENDING_NEXT_BUTTON_INSTALL_PLAN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SELECT_ALL_TRANSACTION, LENDING_SELECT_ALL_TRANSACTION);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SELECT_TRANSACTION_1, LENDING_SELECT_TRANSACTION_1);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SELECT_TRANSACTION_2, LENDING_SELECT_TRANSACTION_2);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_NEXT_BUTTON_TRANSACTION, LENDING_NEXT_BUTTON_TRANSACTION);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SO_GOOD_SELECT_INSTALLMENT_PLAN,LENDING_SO_GOOD_SELECT_INSTALLMENT_PLAN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SELECT_PLAN_3_MONTH, LENDING_SELECT_PLAN_3_MONTH);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SELECT_PLAN_6_MONTH, LENDING_SELECT_PLAN_6_MONTH);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SELECT_PLAN_10_MONTH, LENDING_SELECT_PLAN_10_MONTH);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SO_GOOD_DETAIL_OF_INSTALLMENT_PLAN,LENDING_SO_GOOD_DETAIL_OF_INSTALLMENT_PLAN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_DATA_TRANSACTION, LENDING_DATA_TRANSACTION);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_TERM_AND_CONDITION_DETAIL_INSTALLMENT, LENDING_TERM_AND_CONDITION_DETAIL_INSTALLMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SO_GOOD_CONFIRM_BTN,LENDING_SO_GOOD_CONFIRM_BTN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SO_GOOD_SUCCESFUL, LENDING_SO_GOOD_SUCCESFUL);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BACK_TO_MAIN_PAGE_SO_GOOD, LENDING_BACK_TO_MAIN_PAGE_SO_GOOD);
        oneAppElementHashMap.put(OneAppElementKeys.LENDIND_WORD_CREDIT_CARD_NO, LENDIND_WORD_CREDIT_CARD_NO);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_WORD_SELECTED_TRANSACTION, LENDING_WORD_SELECTED_TRANSACTION);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_WORD_TOTAL_INSTALLMENT, LENDING_WORD_TOTAL_INSTALLMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_WORD_INSTALLMENT_PLAN, LENDING_WORD_INSTALLMENT_PLAN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_WORD_TRANSACTION_DATE, LENDING_WORD_TRANSACTION_DATE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_WORD_TRANSACTION_TIME, LENDING_WORD_TRANSACTION_TIME);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_MAIN_PAGE_UNBILLED, LENDING_MAIN_PAGE_UNBILLED);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_GET_VALUE_TRANSACTION_1, LENDING_GET_VALUE_TRANSACTION_1);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_GET_VALUE_TRANSACTION_2, LENDING_GET_VALUE_TRANSACTION_2);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PARTIAL_SUCCESSFUL, LENDING_PARTIAL_SUCCESSFUL);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_MORE_BUTTON_LANDING_PAGE, LENDING_MORE_BUTTON_LANDING_PAGE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_MORE_BT_SUP_CARD,LENDING_CARD_DETAIL_MORE_BT_SUP_CARD);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_MORE_PRI_HAS_SUP,LENDING_CARD_DETAIL_MORE_PRI_HAS_SUP);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_MORE_BUTTON_SSC_LANDING_PAGE,LENDING_MORE_BUTTON_SSC_LANDING_PAGE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PRODUCT_LANDING_CLOSE_MORE_BTN,LENDING_PRODUCT_LANDING_CLOSE_MORE_BTN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PRODUCT_LANDING_SWIPE_GRAY_WRAP,LENDING_PRODUCT_LANDING_SWIPE_GRAY_WRAP);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PRODUCT_LANDING_BILLED_BTN,LENDING_PRODUCT_LANDING_BILLED_BTN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PRODUCT_LANDING_UNBILLED_BTN,LENDING_PRODUCT_LANDING_UNBILLED_BTN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PRODUCT_LANDING_SELECT_BOX,LENDING_PRODUCT_LANDING_SELECT_BOX);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PRODUCT_LANDING_SELECT_MONTH,LENDING_PRODUCT_LANDING_SELECT_MONTH);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PRODUCT_LANDING_SPENDING,LENDING_PRODUCT_LANDING_SPENDING);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_BUTTON, LENDING_CARD_DETAIL_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_ACCOUNT, LENDING_CARD_DETAIL_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_POINT, LENDING_CARD_DETAIL_POINT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PRODUCT_LANDIND_ACCOUNT, LENDING_PRODUCT_LANDIND_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_DATA_ACCOUNT, LENDING_CARD_DETAIL_DATA_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CREDIT_CARD_SO_FAST, LENDING_CREDIT_CARD_SO_FAST);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_SUP_CARD,LENDING_CARD_DETAIL_SUP_CARD);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_PRI_HAVE_SUP,LENDING_CARD_DETAIL_PRI_HAVE_SUP);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DATAIL_DATA_CARD_NAME, LENDING_CARD_DATAIL_DATA_CARD_NAME);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_HEAD, LENDING_CARD_DETAIL_HEAD);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_PRODUCT_NAME, LENDING_CARD_DETAIL_PRODUCT_NAME);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_CARD_TYPE, LENDING_CARD_DETAIL_CARD_TYPE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_CARD_NUMBER, LENDING_CARD_DETAIL_CARD_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_CARD_HOLDER, LENDING_CARD_DETAIL_CARD_HOLDER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_CARD_LIMIT, LENDING_CARD_DETAIL_CARD_LIMIT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_TOTAL_AMOUNT_DUE, LENDING_CARD_DETAIL_TOTAL_AMOUNT_DUE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_MINIMUM, LENDING_CARD_DETAIL_MINIMUM);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_STATEMENT, LENDING_CARD_DETAIL_STATEMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_PAYMENT_DUE, LENDING_CARD_DETAIL_PAYMENT_DUE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_POINT_DETAIL,LENDING_CARD_DETAIL_POINT_DETAIL);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_OUTSTANDING,LENDING_CARD_DETAIL_OUTSTANDING);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_EXPIRING,LENDING_CARD_DETAIL_EXPIRING);


        oneAppElementHashMap.put(OneAppElementKeys.LENDING_REGISTER_TTB,LENDING_REGISTER_TTB);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_REGIS_BUTTON,LENDING_REGIS_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.REGISTER_ACCEPT_CONDITION,REGISTER_ACCEPT_CONDITION);
        oneAppElementHashMap.put(OneAppElementKeys.REGISTER_NEXT_BUTTON,REGISTER_NEXT_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.REGISTER_CITIZEN_ID,REGISTER_CITIZEN_ID);
        oneAppElementHashMap.put(OneAppElementKeys.REGISTER_NEXT_BUTTON_CITIZEN,REGISTER_NEXT_BUTTON_CITIZEN);
        oneAppElementHashMap.put(OneAppElementKeys.REGISTER_OTP,REGISTER_OTP);
        oneAppElementHashMap.put(OneAppElementKeys.REGISTER_IMAGE,REGISTER_IMAGE);
        oneAppElementHashMap.put(OneAppElementKeys.REGISTER_NEXT_COMPLETE,REGISTER_NEXT_COMPLETE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_APPLY_ESTATEMENT_TERM_CONDITION,LENDING_APPLY_ESTATEMENT_TERM_CONDITION);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_APPLY_ESTATEMENT_CONFIRM,LENDING_APPLY_ESTATEMENT_CONFIRM);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_APPLY_ESTATEMENT_CONFIRM2,LENDING_APPLY_ESTATEMENT_CONFIRM2);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_APPLY_ESTATEMENT_VERIFY_DES,LENDING_APPLY_ESTATEMENT_VERIFY_DES);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_APPLY_ESTATEMENT_CONDITION,LENDING_APPLY_ESTATEMENT_CONDITION);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_APPLY_FLASH_CARD_SELECTED_ACCOUNT,LENDING_APPLY_FLASH_CARD_SELECTED_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_MANAGE_EMAIL,LENDING_ESTATEMENT_MANAGE_EMAIL);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_MANAGE_MAIL_HEADER,LENDING_ESTATEMENT_MANAGE_MAIL_HEADER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_MANAGE_MAIL_NEXT,LENDING_ESTATEMENT_MANAGE_MAIL_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_MANAGE_MAIL_ERROR,LENDING_ESTATEMENT_MANAGE_MAIL_ERROR);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_MANAGE_MAIL_CLEAR,LENDING_ESTATEMENT_MANAGE_MAIL_CLEAR);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_MANAGE_MAIL_INPUT,LENDING_ESTATEMENT_MANAGE_MAIL_INPUT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_MANAGE_MAIL_OTP_1,LENDING_ESTATEMENT_MANAGE_MAIL_OTP_1);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_VERIFY_EMAIL_SUCCESS_BUTTON,LENDING_ESTATEMENT_VERIFY_EMAIL_SUCCESS_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_VERIFY_EMAIL_SUCCESS_TITLE,LENDING_ESTATEMENT_VERIFY_EMAIL_SUCCESS_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_VERIFY_EMAIL_SUCCESS_MESSAGE,LENDING_ESTATEMENT_VERIFY_EMAIL_SUCCESS_MESSAGE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_CHANGE_EMAIL_BUTTON,LENDING_ESTATEMENT_CHANGE_EMAIL_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_CONFIRM_TO_CHANGE_EMAIL,LENDING_ESTATEMENT_CONFIRM_TO_CHANGE_EMAIL);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_CONFIRM_TO_CHANGE_EMAIL2,LENDING_ESTATEMENT_CONFIRM_TO_CHANGE_EMAIL2);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ALREADY_APPLY_ESTATEMENT,LENDING_ALREADY_APPLY_ESTATEMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ALREADY_APPLY_TEXT,LENDING_ALREADY_APPLY_TEXT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BACK_TO_MAIN_PAGE_STATEMENT,LENDING_BACK_TO_MAIN_PAGE_STATEMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_APPLY_STATEMENT_BUTTON,LENDING_APPLY_STATEMENT_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_FLASH_CARD_APPLY_ESTATEMENT_BT,LENDING_FLASH_CARD_APPLY_ESTATEMENT_BT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_APPLY_STATEMENT_BUTTON,LENDING_LOAN_APPLY_STATEMENT_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_HEADER_PAGE,LENDING_LOAN_HEADER_PAGE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_FINISH_PRODUCT ,LENDING_ESTATEMENT_FINISH_PRODUCT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_FINISH_TYPE,LENDING_ESTATEMENT_FINISH_TYPE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ESTATEMENT_FINISH_EMAIL,LENDING_ESTATEMENT_FINISH_EMAIL);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CLICK_CARD_LOAN_B_PLUS,LENDING_CLICK_CARD_LOAN_B_PLUS);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_PAY_BILL_MENU,LENDING_LOAN_PAY_BILL_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_PAID_TEXT,LENDING_LOAN_PAID_TEXT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_OUT_STANDING_TEXT,LENDING_LOAN_OUT_STANDING_TEXT);
        oneAppElementHashMap.put(OneAppElementKeys.LOAN_HOME_SCREEN_BUTTON,LOAN_HOME_SCREEN_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CLICK_CARD_LOAN_C2G,LENDING_CLICK_CARD_LOAN_C2G);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CLICK_CARD_HOME_LOAN,LENDING_CLICK_CARD_HOME_LOAN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_ESTATEMENT_MENU,LENDING_LOAN_ESTATEMENT_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_TOP_UP_MENU,LENDING_LOAN_TOP_UP_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_BOTTOM_SHEET_HEADER,LENDING_LOAN_BOTTOM_SHEET_HEADER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_ACCOUNT_NUMBER,LENDING_LOAN_DETAIL_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_LOAN_SUFFIX,LENDING_LOAN_DETAIL_LOAN_SUFFIX);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_ACCOUNT_NAME,LENDING_LOAN_DETAIL_ACCOUNT_NAME);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_MONTHLY_PAYMENT,LENDING_LOAN_DETAIL_MONTHLY_PAYMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_DUE_DATE,LENDING_LOAN_DETAIL_DUE_DATE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_INTEREST,LENDING_LOAN_DETAIL_INTEREST);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_TENORS,LENDING_LOAN_DETAIL_TENORS);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_START_DATE,LENDING_LOAN_DETAIL_START_DATE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_EXPIRY_DATE,LENDING_LOAN_DETAIL_EXPIRY_DATE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_REMARK,LENDING_LOAN_DETAIL_REMARK);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_DETAIL_PAYMENT,LENDING_LOAN_DETAIL_PAYMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_LOAN_PAYMENT_HISTORY,LENDING_LOAN_PAYMENT_HISTORY);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_TRY_AGAIN_ACCOUNT_SUMMARY,LENDING_TRY_AGAIN_ACCOUNT_SUMMARY);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_SELECT_ACCOUNT,LENDING_SET_ATM_PIN_SELECT_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIM_PRIMARY_MORE_MENU,LENDING_SET_ATM_PIM_PRIMARY_MORE_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_SELECT_SSC,LENDING_SET_ATM_PIN_SELECT_SSC);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_SSC_MORE_BUTTON,LENDING_SET_ATM_SSC_MORE_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_MENU_BUTTON,LENDING_SET_ATM_PIN_MENU_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_PAGE,LENDING_SET_ATM_PIN_PAGE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_INFO_LABEL,LENDING_SET_ATM_PIN_INFO_LABEL);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_ENTER_PIN,LENDING_SET_ATM_PIN_ENTER_PIN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_ENTER_PIN2,LENDING_SET_ATM_PIN_ENTER_PIN2);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_ERROR,LENDING_SET_ATM_PIN_ERROR);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_COMPLETE,LENDING_SET_ATM_PIN_COMPLETE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_CARD_NUMBER,LENDING_SET_ATM_PIN_CARD_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_CHANGED,LENDING_SET_ATM_PIN_CHANGED);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_ATM_PIN_BACK_TO_MAIN,LENDING_SET_ATM_PIN_BACK_TO_MAIN);

        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SELECT_SCC_CARD_ACCOUNT,LENDING_SELECT_SCC_CARD_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_CARD_MANAGEMENT,LENDING_CARD_DETAIL_CARD_MANAGEMENT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_ADJUST,LENDING_CARD_DETAIL_ADJUST);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CARD_DETAIL_BLOCK_CARD,LENDING_CARD_DETAIL_BLOCK_CARD);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_LIMIT_SUP_CARD_SELECTED,LENDING_SET_LIMIT_SUP_CARD_SELECTED);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SETLIMIT_SUP_MORE_BT_SUP_CARD,LENDING_SETLIMIT_SUP_MORE_BT_SUP_CARD);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_LIMIT_PERMANENT_SELECT_CARD,LENDING_SET_LIMIT_PERMANENT_SELECT_CARD);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_LIMIT_PERMANENT_PRIMARY_MORE_MENU,LENDING_SET_LIMIT_PERMANENT_PRIMARY_MORE_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_BUTTON,LENDING_ADJUST_LIMIT_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_INPUT_FIELD,LENDING_ADJUST_LIMIT_INPUT_FIELD);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_HEADER,LENDING_ADJUST_LIMIT_HEADER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_ERROR_LESS_THAN,LENDING_ADJUST_LIMIT_ERROR_LESS_THAN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_ERROR_MORE_THAN,LENDING_ADJUST_LIMIT_ERROR_MORE_THAN);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_ERROR_EQUAL,LENDING_ADJUST_LIMIT_ERROR_EQUAL);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_MESSAGE_TEMP,LENDING_ADJUST_LIMIT_MESSAGE_TEMP);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_NEW_LIMIT,LENDING_ADJUST_LIMIT_NEW_LIMIT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_NEXT_BUTTON,LENDING_ADJUST_LIMIT_NEXT_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_TEMPORARY_LIMIT_SELECT_BOX,LENDING_SET_TEMPORARY_LIMIT_SELECT_BOX);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_TEMPORARY_LIMIT_EDUCATION,LENDING_SET_TEMPORARY_LIMIT_EDUCATION);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_TEMPORARY_EXPIRY_DATE,LENDING_SET_TEMPORARY_EXPIRY_DATE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_TEMPORARY_SELECTED_DATE,LENDING_SET_TEMPORARY_SELECTED_DATE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_TEMPORARY_CLICK_SET,LENDING_SET_TEMPORARY_CLICK_SET);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_TEMPORARY_SUCCESSFULLY,LENDING_SET_TEMPORARY_SUCCESSFULLY);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_SET_TEMPORARY_INFO_SUCCESS,LENDING_SET_TEMPORARY_INFO_SUCCESS);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_TEXT_CONFIRM_LIMIT,LENDING_ADJUST_LIMIT_TEXT_CONFIRM_LIMIT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_CONFIRM_BUTTON,LENDING_ADJUST_LIMIT_CONFIRM_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_COMPLETE,LENDING_ADJUST_LIMIT_COMPLETE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_DETAIL_INFO,LENDING_ADJUST_LIMIT_DETAIL_INFO);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_NEW_CREDIT,LENDING_ADJUST_LIMIT_NEW_CREDIT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_EFFECTIVE_DATE,LENDING_ADJUST_LIMIT_EFFECTIVE_DATE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_TEMP_EXPIRY_DATE,LENDING_ADJUST_LIMIT_TEMP_EXPIRY_DATE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ADJUST_LIMIT_BACK_TO_MAIN_PAGE,LENDING_ADJUST_LIMIT_BACK_TO_MAIN_PAGE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_CREDIT_CARD_SELECT,LENDING_ACTIVATE_CREDIT_CARD_SELECT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_SSC_CARD_SELECTED,LENDING_ACTIVATE_SSC_CARD_SELECTED);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_CARD_PRIMARY_ENTER_CARD_NUMBER,LENDING_ACTIVATE_CARD_PRIMARY_ENTER_CARD_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_CARD_HEADER,LENDING_ACTIVATE_CARD_HEADER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_ENTER_NUMBER_PIN0,LENDING_ACTIVATE_ENTER_NUMBER_PIN0);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_ENTER_NUMBER_PIN1,LENDING_ACTIVATE_ENTER_NUMBER_PIN1);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_ENTER_NUMBER_PIN2,LENDING_ACTIVATE_ENTER_NUMBER_PIN2);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_ENTER_NUMBER_PIN3,LENDING_ACTIVATE_ENTER_NUMBER_PIN3);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_ENTER_NUMBER_PIN5,LENDING_ACTIVATE_ENTER_NUMBER_PIN5);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_ENTER_NUMBER_PIN6,LENDING_ACTIVATE_ENTER_NUMBER_PIN6);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_ENTER_NUMBER_PIN7,LENDING_ACTIVATE_ENTER_NUMBER_PIN7);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_ENTER_NUMBER_PIN8,LENDING_ACTIVATE_ENTER_NUMBER_PIN8);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_CARD_ERROR_ENTER_CARD_NUMBER,LENDING_ACTIVATE_CARD_ERROR_ENTER_CARD_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_CARD_ERROR_ENTER_CVV,LENDING_ACTIVATE_CARD_ERROR_ENTER_CVV);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_CARD_SUCCESSFULLY,LENDING_ACTIVATE_CARD_SUCCESSFULLY);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_CARD_TEXT_CARD_NUMBER,LENDING_ACTIVATE_CARD_TEXT_CARD_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_CARD_TEXT_CAN_USE,LENDING_ACTIVATE_CARD_TEXT_CAN_USE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_ACTIVATE_CARD_COMPLETE_BUTTON,LENDING_ACTIVATE_CARD_COMPLETE_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BLOCK_CARD_SELECT_ACCOUNT,LENDING_BLOCK_CARD_SELECT_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BLOCK_CARD_MENU_BUTTON,LENDING_BLOCK_CARD_MENU_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BLOCK_CARD_PAGE_HEADER,LENDING_BLOCK_CARD_PAGE_HEADER);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BLOCK_CARD_PAGE_CONFIRM,LENDING_BLOCK_CARD_PAGE_CONFIRM);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BLOCK_CARD_SUCCESSFULLY,LENDING_BLOCK_CARD_SUCCESSFULLY);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BLOCK_CARD_INFO_1,LENDING_BLOCK_CARD_INFO_1);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BLOCK_CARD_INFO_2,LENDING_BLOCK_CARD_INFO_2);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BLOCK_CARD_INFO_3,LENDING_BLOCK_CARD_INFO_3);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BLOCK_CARD_DATE,LENDING_BLOCK_CARD_DATE);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_BLOCK_CARD_TIME,LENDING_BLOCK_CARD_TIME);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_TRANSFER_FLASH_SELECT_ACCOUNT,LENDING_CASH_TRANSFER_FLASH_SELECT_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_TRANSFER_CREDIT_SELECT_ACCOUNT,LENDING_CASH_TRANSFER_CREDIT_SELECT_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_CASH_ADVANCE_SELECT_ACCOUNT,LENDING_CASH_ADVANCE_SELECT_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PRODUCT_LANDING_PRIMARY_ACCOUNT,LENDING_PRODUCT_LANDING_PRIMARY_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_PRODUCT_LANDING_SSC_ACCOUNT,LENDING_PRODUCT_LANDING_SSC_ACCOUNT);

        oneAppElementHashMap.put(OneAppElementKeys.LENDING_FLEXI_LOAN_APPLY_BUTTON,LENDING_FLEXI_LOAN_APPLY_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_FLEXI_LOAN_CREDIT_CARD_MENU,LENDING_FLEXI_LOAN_CREDIT_CARD_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_FLEXI_LOAN_SELECTED_SO_SMART,LENDING_FLEXI_LOAN_SELECTED_SO_SMART);
        oneAppElementHashMap.put(OneAppElementKeys.LENDING_FLEXI_LOAN_APPLY_CREDIT,LENDING_FLEXI_LOAN_APPLY_CREDIT);
    }
}
