package com.ttbbank.oneapp.framework.element.android;

import com.ttbbank.oneapp.framework.FindBy;
import com.ttbbank.oneapp.framework.OneAppElement;
import com.ttbbank.oneapp.framework.OneAppElementKeys;
import java.util.Map;

public class Pb1AndroidOneAppElements {
    private Pb1AndroidOneAppElements() {}

    //PB 1
    private static final OneAppElement PB1_HOME = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/ll_tap", 0);
    private static final OneAppElement PB1_ACCOUNT = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/ll_tap", 1);
    private static final OneAppElement PB1_MORE = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/ll_tap", 3);
    private static final OneAppElement PB1_SETTING = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/settingMenuName", 0);
    private static final OneAppElement PB1_SETTING_BACK = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/settingIconBack");
    private static final OneAppElement PB1_PERSONAL_INFORMATION = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/settingTextTitle");
    private static final OneAppElement PB1_LANGUAGE = new OneAppElement(FindBy.XPATH, "//android.widget.ScrollView/android.view.ViewGroup/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[8]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.TextView[1]");
    private static final OneAppElement PB1_LANGUAGE_TH = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/radio_thai"); //ภาษาไทย
    private static final OneAppElement PB1_LANGUAGE_EN = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/radio_english"); //English
    private static final OneAppElement PB1_LANGUAGE_BACK = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/change_language_back_button");
    
    private static final OneAppElement PB1_KEYPAD_DONE_EN = new OneAppElement(FindBy.RESOURCE_ID, "Done");
    private static final OneAppElement PB1_KEYPAD_DONE_TH = new OneAppElement(FindBy.RESOURCE_ID, "ถัดไป");
    private static final OneAppElement PB1_WITHDRAW = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/quick_action_button_label", 2);
    private static final OneAppElement PB1_REGISTER_TTB = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/full_width_primary_btn");
    private static final OneAppElement PB1_ACCEPT_T_AND_C = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/terms_and_conditions_checkbox");
    private static final OneAppElement PB1_T_AND_C_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/terms_and_conditions_next_btn");
    private static final OneAppElement PB1_INPUT_CID = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/edt_component");
    private static final OneAppElement PB1_ENTER_CID_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/next_btn");
    private static final OneAppElement PB1_ENTER_PIN_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/sub_title_text");
    private static final OneAppElement PB1_OTP_HEADER = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/title_custom_text");
    private static final OneAppElement PB1_OTP_REF = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/otp_verify_ref");
    private static final OneAppElement PB1_ACTIVATE_NEXT_EN = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/complete_next_btn");
    private static final OneAppElement PB1_ACTIVATE_NEXT_TH = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/complete_next_btn");
    private static final OneAppElement PB1_HOME_INTRO_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/buttonNext");
    private static final OneAppElement PB1_ACCOUNT_INTRO_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/buttonNext");

    private static final OneAppElement PB1_DEPOSIT_ACCOUNT_LIST = new OneAppElement(FindBy.XPATH, "//*[@resource-id='com.ttbbank.oneapp.vit:id/itemCardDepositLayout'][1]");
    private static final OneAppElement PB1_ACCOUNT_NICKNAME = new OneAppElement(FindBy.RESOURCE_ID, "adLb_account_nickname_label");
    private static final OneAppElement PB1_MORE_MENU = new OneAppElement(FindBy.RESOURCE_ID, "adMn_more_option_menu");
    private static final OneAppElement PB1_MENU_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "adLb_more_action_label");
    private static final OneAppElement PB1_CARDLESS_WITHDRAW = new OneAppElement(FindBy.RESOURCE_ID, "adMn_withdraw_menu");
    private static final OneAppElement PB1_CARDLESS_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "titleID");
    private static final OneAppElement PB1_CARDLESS_AC_TYPE = new OneAppElement(FindBy.RESOURCE_ID, "accountName_0");
    private static final OneAppElement PB1_CARDLESS_FROM_AC = new OneAppElement(FindBy.RESOURCE_ID, "accountNumber_0");
    private static final OneAppElement PB1_CARDLESS_BALANCE = new OneAppElement(FindBy.RESOURCE_ID, "accountMoney_0");
    private static final OneAppElement PB1_CARDLESS_AMOUNT_FIELD = new OneAppElement(FindBy.RESOURCE_ID, "cardless-enter-amount-field_input");
    private static final OneAppElement PB1_CARDLESS_FIELD_HELP_TEXT = new OneAppElement(FindBy.RESOURCE_ID, "cardless-enter-amount-field_helptext");
    private static final OneAppElement PB1_CARDLESS_BACK_BUTTON = new OneAppElement(FindBy.XPATH, "//*[@resource-id='__next']/android.view.View[1]/android.view.View/android.view.View/android.view.View[1]/android.widget.Button");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT100 = new OneAppElement(FindBy.XPATH, "//*[@text='100']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT300 = new OneAppElement(FindBy.XPATH, "//*[@text='300']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT500 = new OneAppElement(FindBy.XPATH, "//*[@text='500']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT900 = new OneAppElement(FindBy.XPATH, "//*[@text='900']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT1000 = new OneAppElement(FindBy.XPATH, "//*[@text='1,000']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT2000 = new OneAppElement(FindBy.XPATH, "//*[@text='2,000']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT3000 = new OneAppElement(FindBy.XPATH, "//*[@text='3,000']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT4000 = new OneAppElement(FindBy.XPATH, "//*[@text='4,000']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT5000 = new OneAppElement(FindBy.XPATH, "//*[@text='5,000']");
    private static final OneAppElement PB1_CARDLESS_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "cardless-enter-button");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_TITLE = new OneAppElement(FindBy.XPATH, "//*[@resource-id='__next']/android.view.View[1]/android.view.View/android.view.View/android.widget.TextView");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_WITHDRAW_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "accountNameIdentity");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_AC_TYPE = new OneAppElement(FindBy.RESOURCE_ID, "accountNameIdentity_value");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_FROM = new OneAppElement(FindBy.XPATH, "//*[@resource-id='accountNameIdentity_value']/following-sibling::android.widget.TextView");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_AMOUNT_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "accountAmountValueIdentity");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_AMOUNT = new OneAppElement(FindBy.RESOURCE_ID, "accountAmountValueIdentity_value");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_BANNER1 = new OneAppElement(FindBy.XPATH, "//*[@resource-id='cardless-confirm-banner_desc']/android.widget.TextView[1]");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_BANNER2 = new OneAppElement(FindBy.XPATH, "//*[@resource-id='cardless-confirm-banner_desc']/android.widget.TextView[2]");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_GENERATE = new OneAppElement(FindBy.RESOURCE_ID, "cardless-confirm-button");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_BACK = new OneAppElement(FindBy.XPATH, "//*[@resource-id='__next']/android.view.View[1]/android.view.View/android.view.View/android.view.View[1]/android.widget.Button");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_PIN_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/title_pin");
    private static final OneAppElement PB1_CARDLESS_EXPIRE_MESSAGE = new OneAppElement(FindBy.RESOURCE_ID, "cardless-withdrawal-pin-access-expired");
    private static final OneAppElement PB1_CARDLESS_PIN0 = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/pin_key_0");
    private static final OneAppElement PB1_CARDLESS_PIN1 = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/pin_key_1");
    private static final OneAppElement PB1_CARDLESS_PIN2 = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/pin_key_2");
    private static final OneAppElement PB1_CARDLESS_PIN3 = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/pin_key_3");
    private static final OneAppElement PB1_CARDLESS_CODE_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "titleID");
    private static final OneAppElement PB1_CARDLESS_CODE_PIN_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "cardless-withdrawal-pin-heading");
    private static final OneAppElement PB1_CARDLESS_CODE = new OneAppElement(FindBy.RESOURCE_ID, "cardless-withdrawal-pin-access-label");
    private static final OneAppElement PB1_CARDLESS_CODE_TIMER = new OneAppElement(FindBy.RESOURCE_ID, "cardless-withdrawal-pin-timer");
    private static final OneAppElement PB1_CARDLESS_CODE_SUBHEADER = new OneAppElement(FindBy.RESOURCE_ID, "cardless-withdrawal-pin-sub-header");
    private static final OneAppElement PB1_CARDLESS_WITHDRAW_FROM = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataLabel_1");
    private static final OneAppElement PB1_CARDLESS_ACCOUNT_TYPE = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataValue_1");
    private static final OneAppElement PB1_CARDLESS_AMOUNT = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataLabel_2");
    private static final OneAppElement PB1_CARDLESS_AMOUNT_NO = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataValue_2");
    private static final OneAppElement PB1_CARDLESS_GENERATE = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataLabel_3");
    private static final OneAppElement PB1_CARDLESS_GENERATE_TIME = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataValue_3");
    private static final OneAppElement PB1_CARDLESS_EXPIRY = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataLabel_4");
    private static final OneAppElement PB1_CARDLESS_EXPIRY_TIME = new OneAppElement(FindBy.RESOURCE_ID, "ColumnDataValue_4");
    private static final OneAppElement PB1_CARDLESS_CODE_DONE = new OneAppElement(FindBy.RESOURCE_ID, "cardless-withdrawal-pin-deactivate-done-button");
    private static final OneAppElement PB1_CARDLESS_CODE_DEACTIVE = new OneAppElement(FindBy.RESOURCE_ID, "cardless-withdrawal-pin-deactivate-button");
    private static final OneAppElement PB1_CARDLESS_PIN_EXPIRE_TITLE = new OneAppElement(FindBy.XPATH, "//*[@resource-id='cardless-withdrawal-pin-bottom-sheet-deactivate']/android.view.View/android.widget.TextView");
    private static final OneAppElement PB1_CARDLESS_PIN_EXPIRE_TITLE_HOME = new OneAppElement(FindBy.XPATH, "//*[@resource-id='cardless-withdrawal-pin-bottom-sheet-deactivate']/android.view.View/android.widget.TextView");
    private static final OneAppElement PB1_CARDLESS_PIN_CANCEL = new OneAppElement(FindBy.XPATH, "cardless-withdrawal-pin-cancel-button");
    private static final OneAppElement PB1_CARDLESS_PIN_OK = new OneAppElement(FindBy.RESOURCE_ID, "cardless-withdrawal-pin-confirm-button");
    private static final OneAppElement PB1_CARDLESS_DEACTIVE_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "deactivate-pin-title-id");
    private static final OneAppElement PB1_CARDLESS_DEACTIVE_MESSAGE = new OneAppElement(FindBy.RESOURCE_ID, "deactivate-pin-sub-title-id");
    private static final OneAppElement PB1_CARDLESS_DEACTIVE_DONE = new OneAppElement(FindBy.RESOURCE_ID, "cardless-withdrawal-pin-deactivate-done-button");
    private static final OneAppElement PB1_CARDLESS_DEACTIVE_GENERATE = new OneAppElement(FindBy.RESOURCE_ID, "cardless-withdrawal-pin-deactivate-generate-pin-button");

    private static final OneAppElement PB1_EKYC_REGISTER_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/title_custom_text");
    private static final OneAppElement PB1_EKYC_REGISTER_METHOD = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/activate_option_step_label");
    private static final OneAppElement PB1_EKYC_OPEN_AC = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/activation_active_option_label");
    private static final OneAppElement PB1_EKYC_OPEN_AC_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/activate_option_next_button");
    private static final OneAppElement PB1_EKYC_OPEN_AC_TITLE = new OneAppElement(FindBy.XPATH, "//*[@resource-id='__next']/android.view.View[2]/android.view.View");
    private static final OneAppElement PB1_EKYC_ALLFREE = new OneAppElement(FindBy.RESOURCE_ID, "LabelText_225");
    private static final OneAppElement PB1_EKYC_NOFIX = new OneAppElement(FindBy.RESOURCE_ID, "LabelText_221");
    private static final OneAppElement PB1_EKYC_SELECTAC_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-product-list-button");
    private static final OneAppElement PB1_EKYC_PRODUCT_IMG_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-product-brief-button");
    private static final OneAppElement PB1_EKYC_WIFIOFF_MESSAGE1 = new OneAppElement(FindBy.XPATH, "//*[@resource-id='ekyc-mobile-number-check-banner_desc']/android.view.View");
    private static final OneAppElement PB1_EKYC_CHECKMOBILE_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-mobile-number-check-button");
    private static final OneAppElement PB1_EKYC_WIFIOFF_TITLE = new OneAppElement(FindBy.XPATH, "//android.webkit.WebView/android.webkit.WebView/android.view.View[2]/android.view.View[4]/android.view.View/android.view.View/android.view.View");
    private static final OneAppElement PB1_EKYC_WIFIOFF_MESSAGE2 = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-mobile-number-check-poopup-title");
    private static final OneAppElement PB1_EKYC_WIFI_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "primaryButton");
    private static final OneAppElement PB1_EKYC_STEP_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "step_label_id");
    private static final OneAppElement PB1_EKYC_TC_ACCEPT1 = new OneAppElement(FindBy.RESOURCE_ID, "1");
    private static final OneAppElement PB1_EKYC_TC_ACCEPT2 = new OneAppElement(FindBy.RESOURCE_ID, "2");
    private static final OneAppElement PB1_EKYC_TC_ACCEPT3 = new OneAppElement(FindBy.RESOURCE_ID, "3");
    private static final OneAppElement PB1_EKYC_TC_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-terms-condition-button");
    private static final OneAppElement PB1_EKYC_SCAN_TIPS = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-tips-to-scan-title");
    private static final OneAppElement PB1_EKYC_SCAN_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-tips-to-scan-button");
    private static final OneAppElement PB1_EKYC_SCAN_ALLOW = new OneAppElement(FindBy.RESOURCE_ID, "com.android.packageinstaller:id/permission_allow_button");
    private static final OneAppElement PB1_EKYC_SCAN_BUTTON = new OneAppElement(FindBy.RESOURCE_ID, "com.ttbbank.oneapp.vit:id/img_capture");
    private static final OneAppElement PB1_EKYC_PERSONAL_DETAILS = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-title");
    private static final OneAppElement PB1_EKYC_PERSONAL_ID = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-field-id-number_input");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "selectBox");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE_MR = new OneAppElement(FindBy.XPATH, "//*[@resource-id='android:id/text1'][1]");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE_MISS = new OneAppElement(FindBy.XPATH, "//*[@resource-id='android:id/text1'][2]");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE_MRS = new OneAppElement(FindBy.XPATH, "//*[@resource-id='android:id/text1'][3]");
    private static final OneAppElement PB1_EKYC_PERSONAL_FNAME_TH = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-field-first-name_input");
    private static final OneAppElement PB1_EKYC_PERSONAL_LNAME_TH = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-field-last-name_input");
    private static final OneAppElement PB1_EKYC_PERSONAL_FNAME_EN = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-field-first-name-en_input");
    private static final OneAppElement PB1_EKYC_PERSONAL_LNAME_EN = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-field-first-last-en_input");
    private static final OneAppElement PB1_EKYC_PERSONAL_DOB = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-field-dob_dateInput");
    private static final OneAppElement PB1_EKYC_PERSONAL_CID_ISSUE = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-field-issue-date_dateInput");
    private static final OneAppElement PB1_EKYC_PERSONAL_CID_EXPIRY = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-field-expiry-date_dateInput");
    private static final OneAppElement PB1_EKYC_PERSONAL_CID_NONEXP = new OneAppElement(FindBy.RESOURCE_ID, "1");
    private static final OneAppElement PB1_EKYC_PERSONAL_YEAR_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "android:id/date_picker_header_year");
    private static final OneAppElement PB1_EKYC_PERSONAL_YEAR_SELECT = new OneAppElement(FindBy.RESOURCE_ID, "android:id/date_picker_year_picker");
    private static final OneAppElement PB1_EKYC_PERSONAL_YEAR_SELECT1 = new OneAppElement(FindBy.RESOURCE_ID, "android:id/text1");
    private static final OneAppElement PB1_EKYC_PERSONAL_DATE_SELECT = new OneAppElement(FindBy.RESOURCE_ID, "android:id/date_picker_header_date");
    private static final OneAppElement PB1_EKYC_PERSONAL_MONTH_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "android:id/next");
    private static final OneAppElement PB1_EKYC_PERSONAL_MONTH_PREVIOUS = new OneAppElement(FindBy.RESOURCE_ID, "android:id/prev");
    private static final OneAppElement PB1_EKYC_PERSONAL_DATE_SET = new OneAppElement(FindBy.RESOURCE_ID, "android:id/button1");
    private static final OneAppElement PB1_EKYC_PERSONAL_LASER_CODE = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-field-bank-card-code_input");
    private static final OneAppElement PB1_EKYC_PERSONAL_CONFIRM = new OneAppElement(FindBy.RESOURCE_ID, "personal-details-button");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_ANSWER1 = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-fatca-answer-no_0");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_ANSWER2 = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-fatca-answer-no_1");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_ANSWER_YES = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-fatca-answer-yes_1");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_NEXT = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-fatca-button");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_FAIL_TITLE = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-fatca-error-fail-text");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_FAIL_MESSAGE = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-fatca-error-msg-text");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_FAIL_BUTTON = new OneAppElement(FindBy.RESOURCE_ID, "ekyc-fatca-error-button");


    public static void init(Map<String, OneAppElement> oneAppElementHashMap) {
        //PB 1
    	oneAppElementHashMap.put(OneAppElementKeys.PB1_HOME, PB1_HOME);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACCOUNT, PB1_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_MORE, PB1_MORE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_SETTING, PB1_SETTING);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_SETTING_BACK, PB1_SETTING_BACK);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_PERSONAL_INFORMATION, PB1_PERSONAL_INFORMATION);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_LANGUAGE, PB1_LANGUAGE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_LANGUAGE_TH, PB1_LANGUAGE_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_LANGUAGE_EN, PB1_LANGUAGE_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_LANGUAGE_BACK, PB1_LANGUAGE_BACK);
        
        oneAppElementHashMap.put(OneAppElementKeys.PB1_KEYPAD_DONE_EN, PB1_KEYPAD_DONE_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_KEYPAD_DONE_TH, PB1_KEYPAD_DONE_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_WITHDRAW, PB1_WITHDRAW);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_REGISTER_TTB, PB1_REGISTER_TTB);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACCEPT_T_AND_C, PB1_ACCEPT_T_AND_C);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_T_AND_C_NEXT, PB1_T_AND_C_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_INPUT_CID, PB1_INPUT_CID);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ENTER_CID_NEXT, PB1_ENTER_CID_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ENTER_PIN_TITLE, PB1_ENTER_PIN_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_OTP_HEADER, PB1_OTP_HEADER);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_OTP_REF, PB1_OTP_REF);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACTIVATE_NEXT_EN, PB1_ACTIVATE_NEXT_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACTIVATE_NEXT_TH, PB1_ACTIVATE_NEXT_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_HOME_INTRO_NEXT, PB1_HOME_INTRO_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACCOUNT_INTRO_NEXT, PB1_ACCOUNT_INTRO_NEXT);

        oneAppElementHashMap.put(OneAppElementKeys.PB1_DEPOSIT_ACCOUNT_LIST, PB1_DEPOSIT_ACCOUNT_LIST);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACCOUNT_NICKNAME, PB1_ACCOUNT_NICKNAME);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_MORE_MENU, PB1_MORE_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_MENU_TITLE, PB1_MENU_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_WITHDRAW, PB1_CARDLESS_WITHDRAW);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_TITLE, PB1_CARDLESS_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_AC_TYPE, PB1_CARDLESS_AC_TYPE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_FROM_AC, PB1_CARDLESS_FROM_AC);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_BALANCE, PB1_CARDLESS_BALANCE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_AMOUNT_FIELD, PB1_CARDLESS_AMOUNT_FIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_FIELD_HELP_TEXT, PB1_CARDLESS_FIELD_HELP_TEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_BACK_BUTTON, PB1_CARDLESS_BACK_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT100, PB1_CARDLESS_SELECT_AMOUNT100);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT300, PB1_CARDLESS_SELECT_AMOUNT300);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT500, PB1_CARDLESS_SELECT_AMOUNT500);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT900, PB1_CARDLESS_SELECT_AMOUNT900);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT1000, PB1_CARDLESS_SELECT_AMOUNT1000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT2000, PB1_CARDLESS_SELECT_AMOUNT2000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT3000, PB1_CARDLESS_SELECT_AMOUNT3000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT4000, PB1_CARDLESS_SELECT_AMOUNT4000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT5000, PB1_CARDLESS_SELECT_AMOUNT5000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_NEXT, PB1_CARDLESS_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_TITLE, PB1_CARDLESS_CONFIRM_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_WITHDRAW_TITLE, PB1_CARDLESS_CONFIRM_WITHDRAW_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_AC_TYPE, PB1_CARDLESS_CONFIRM_AC_TYPE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_FROM, PB1_CARDLESS_CONFIRM_FROM);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_AMOUNT_TITLE, PB1_CARDLESS_CONFIRM_AMOUNT_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_AMOUNT, PB1_CARDLESS_CONFIRM_AMOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_BANNER1, PB1_CARDLESS_CONFIRM_BANNER1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_BANNER2, PB1_CARDLESS_CONFIRM_BANNER2);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_GENERATE, PB1_CARDLESS_CONFIRM_GENERATE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_BACK, PB1_CARDLESS_CONFIRM_BACK);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_EXPIRE_MESSAGE, PB1_CARDLESS_EXPIRE_MESSAGE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_PIN_TITLE, PB1_CARDLESS_CONFIRM_PIN_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN0, PB1_CARDLESS_PIN0);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN1, PB1_CARDLESS_PIN1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN2, PB1_CARDLESS_PIN2);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN3, PB1_CARDLESS_PIN3);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_TITLE, PB1_CARDLESS_CODE_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_PIN_TITLE, PB1_CARDLESS_CODE_PIN_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE, PB1_CARDLESS_CODE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_TIMER, PB1_CARDLESS_CODE_TIMER);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_SUBHEADER, PB1_CARDLESS_CODE_SUBHEADER);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_WITHDRAW_FROM, PB1_CARDLESS_WITHDRAW_FROM);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_ACCOUNT_TYPE, PB1_CARDLESS_ACCOUNT_TYPE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_AMOUNT, PB1_CARDLESS_AMOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_AMOUNT_NO, PB1_CARDLESS_AMOUNT_NO);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_GENERATE, PB1_CARDLESS_GENERATE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_GENERATE_TIME, PB1_CARDLESS_GENERATE_TIME);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_EXPIRY, PB1_CARDLESS_EXPIRY);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_EXPIRY_TIME, PB1_CARDLESS_EXPIRY_TIME);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_DONE, PB1_CARDLESS_CODE_DONE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_DEACTIVE, PB1_CARDLESS_CODE_DEACTIVE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN_EXPIRE_TITLE, PB1_CARDLESS_PIN_EXPIRE_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN_EXPIRE_TITLE_HOME, PB1_CARDLESS_PIN_EXPIRE_TITLE_HOME);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN_CANCEL, PB1_CARDLESS_PIN_CANCEL);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN_OK, PB1_CARDLESS_PIN_OK);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_DEACTIVE_TITLE, PB1_CARDLESS_DEACTIVE_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_DEACTIVE_MESSAGE, PB1_CARDLESS_DEACTIVE_MESSAGE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_DEACTIVE_DONE, PB1_CARDLESS_DEACTIVE_DONE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_DEACTIVE_GENERATE, PB1_CARDLESS_DEACTIVE_GENERATE);

        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_REGISTER_TITLE, PB1_EKYC_REGISTER_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_REGISTER_METHOD, PB1_EKYC_REGISTER_METHOD);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_OPEN_AC, PB1_EKYC_OPEN_AC);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_OPEN_AC_NEXT, PB1_EKYC_OPEN_AC_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_OPEN_AC_TITLE, PB1_EKYC_OPEN_AC_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_ALLFREE, PB1_EKYC_ALLFREE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_NOFIX, PB1_EKYC_NOFIX);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_SELECTAC_NEXT, PB1_EKYC_SELECTAC_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PRODUCT_IMG_NEXT, PB1_EKYC_PRODUCT_IMG_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_WIFIOFF_MESSAGE1, PB1_EKYC_WIFIOFF_MESSAGE1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_CHECKMOBILE_NEXT, PB1_EKYC_CHECKMOBILE_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_WIFIOFF_TITLE, PB1_EKYC_WIFIOFF_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_WIFIOFF_MESSAGE2, PB1_EKYC_WIFIOFF_MESSAGE2);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_WIFI_NEXT, PB1_EKYC_WIFI_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_STEP_TITLE, PB1_EKYC_STEP_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_TC_ACCEPT1, PB1_EKYC_TC_ACCEPT1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_TC_ACCEPT2, PB1_EKYC_TC_ACCEPT2);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_TC_ACCEPT3, PB1_EKYC_TC_ACCEPT3);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_TC_NEXT, PB1_EKYC_TC_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_SCAN_TIPS, PB1_EKYC_SCAN_TIPS);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_SCAN_NEXT, PB1_EKYC_SCAN_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_SCAN_ALLOW, PB1_EKYC_SCAN_ALLOW);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_SCAN_BUTTON, PB1_EKYC_SCAN_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_DETAILS, PB1_EKYC_PERSONAL_DETAILS);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_ID, PB1_EKYC_PERSONAL_ID);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE, PB1_EKYC_PERSONAL_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE_MR, PB1_EKYC_PERSONAL_TITLE_MR);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE_MISS, PB1_EKYC_PERSONAL_TITLE_MISS);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE_MRS, PB1_EKYC_PERSONAL_TITLE_MRS);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FNAME_TH, PB1_EKYC_PERSONAL_FNAME_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_LNAME_TH, PB1_EKYC_PERSONAL_LNAME_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FNAME_EN, PB1_EKYC_PERSONAL_FNAME_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_LNAME_EN, PB1_EKYC_PERSONAL_LNAME_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_DOB, PB1_EKYC_PERSONAL_DOB);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_CID_ISSUE, PB1_EKYC_PERSONAL_CID_ISSUE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_CID_EXPIRY, PB1_EKYC_PERSONAL_CID_EXPIRY);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_CID_NONEXP, PB1_EKYC_PERSONAL_CID_NONEXP);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_YEAR_TITLE, PB1_EKYC_PERSONAL_YEAR_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_YEAR_SELECT, PB1_EKYC_PERSONAL_YEAR_SELECT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_YEAR_SELECT1, PB1_EKYC_PERSONAL_YEAR_SELECT1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_DATE_SELECT, PB1_EKYC_PERSONAL_DATE_SELECT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_MONTH_NEXT, PB1_EKYC_PERSONAL_MONTH_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_MONTH_PREVIOUS, PB1_EKYC_PERSONAL_MONTH_PREVIOUS);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_DATE_SET, PB1_EKYC_PERSONAL_DATE_SET);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_LASER_CODE, PB1_EKYC_PERSONAL_LASER_CODE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_CONFIRM, PB1_EKYC_PERSONAL_CONFIRM);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_ANSWER1, PB1_EKYC_PERSONAL_FATCA_ANSWER1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_ANSWER2, PB1_EKYC_PERSONAL_FATCA_ANSWER2);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_ANSWER_YES, PB1_EKYC_PERSONAL_FATCA_ANSWER_YES);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_NEXT, PB1_EKYC_PERSONAL_FATCA_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_FAIL_TITLE, PB1_EKYC_PERSONAL_FATCA_FAIL_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_FAIL_MESSAGE, PB1_EKYC_PERSONAL_FATCA_FAIL_MESSAGE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_FAIL_BUTTON, PB1_EKYC_PERSONAL_FATCA_FAIL_BUTTON);

    }
}
