package com.ttbbank.oneapp.framework.element.ios;

import com.ttbbank.oneapp.framework.FindBy;
import com.ttbbank.oneapp.framework.OneAppElement;
import com.ttbbank.oneapp.framework.OneAppElementKeys;
import java.util.Map;

public class Pb1iOSOneAppElements {
    private Pb1iOSOneAppElements() { }

    //PB 1
    private static final OneAppElement PB1_HOME = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeTabBar[@type='XCUIElementTypeTabBar']/XCUIElementTypeOther/XCUIElementTypeButton");
    private static final OneAppElement PB1_ACCOUNT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeTabBar[@type='XCUIElementTypeTabBar']/XCUIElementTypeOther/XCUIElementTypeButton[2]");
    private static final OneAppElement PB1_MORE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeTabBar[@type='XCUIElementTypeTabBar']/XCUIElementTypeOther/XCUIElementTypeButton[4]");
    private static final OneAppElement PB1_SETTING = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeScrollView/XCUIElementTypeOther[3]/XCUIElementTypeOther");
    private static final OneAppElement PB1_SETTING_BACK = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton");
    private static final OneAppElement PB1_PERSONAL_INFORMATION = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeScrollView/XCUIElementTypeOther[1]/XCUIElementTypeTable/XCUIElementTypeOther/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_LANGUAGE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name='Title setting'][16]");
    private static final OneAppElement PB1_LANGUAGE_TH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name='ภาษาไทย']"); //ภาษาไทย
    private static final OneAppElement PB1_LANGUAGE_EN = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name='English']"); //English
    private static final OneAppElement PB1_LANGUAGE_BACK = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='BlueMedium24PxChevronLeft']");
    
    private static final OneAppElement PB1_KEYPAD_DONE_EN = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeToolbar[@name='Toolbar']/XCUIElementTypeOther/XCUIElementTypeOther");
    private static final OneAppElement PB1_KEYPAD_DONE_TH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='เสร็จสิ้น']");
    private static final OneAppElement PB1_KEYPAD_ALLOW = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther[3]");
    private static final OneAppElement PB1_WITHDRAW = new OneAppElement(FindBy.XPATH, "//*[@type='XCUIElementTypeCell']/XCUIElementTypeOther[4]/XCUIElementTypeButton[3]");
    private static final OneAppElement PB1_REGISTER_TTB = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='Bottom sheet primary button']");
    private static final OneAppElement PB1_ACCEPT_T_AND_C = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeButton[2]");
    private static final OneAppElement PB1_T_AND_C_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeButton[3]");
    private static final OneAppElement PB1_INPUT_CID = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB1_ENTER_CID_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeButton[2]");
    private static final OneAppElement PB1_ENTER_PIN_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeStaticText[2]");
    private static final OneAppElement PB1_OTP_HEADER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeStaticText[2]");
    private static final OneAppElement PB1_OTP_REF = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeStaticText[3]");
    private static final OneAppElement PB1_ACTIVATE_NEXT_EN = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='Next']");
    private static final OneAppElement PB1_ACTIVATE_NEXT_TH = new OneAppElement(FindBy.ACCESSIBILITY_ID, "ถัดไป");
    private static final OneAppElement PB1_HOME_INTRO_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeButton");
    private static final OneAppElement PB1_ACCOUNT_INTRO_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeButton");

    private static final OneAppElement PB1_DEPOSIT_ACCOUNT_LIST = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[2]");
    private static final OneAppElement PB1_ACCOUNT_NICKNAME = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[9]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_MORE_MENU = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[12]/XCUIElementTypeOther[4]");
    private static final OneAppElement PB1_MENU_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[45]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_WITHDRAW = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[46]/XCUIElementTypeOther");
    private static final OneAppElement PB1_CARDLESS_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_AC_TYPE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[4]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_FROM_AC = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[5]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_BALANCE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[6]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_AMOUNT_FIELD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeTextField");
    private static final OneAppElement PB1_CARDLESS_FIELD_HELP_TEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[9]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_FIELD_HELP_TEXT1 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[10]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_AC_TYPEA = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[5]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_FROM_ACA = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[6]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_BALANCEA = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[7]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_FIELD_HELP_TEXTA = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[19]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_FIELD_HELP_TEXT1A = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[20]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_BACK_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[2]/XCUIElementTypeButton");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT100 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='100']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT300 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='300']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT500 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='500']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT900 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='900']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT1000 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='1,000']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT2000 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='2,000']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT3000 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='3,000']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT4000 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='4,000']");
    private static final OneAppElement PB1_CARDLESS_SELECT_AMOUNT5000 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='5,000']");
    private static final OneAppElement PB1_CARDLESS_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeButton");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_WITHDRAW_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[3]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_AC_TYPE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[4]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_FROM = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[5]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_AMOUNT_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[6]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_AMOUNT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[7]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_BANNER1 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[8]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_BANNER2 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[9]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_GENERATE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeButton");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_BACK = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[2]/XCUIElementTypeButton");
    private static final OneAppElement PB1_CARDLESS_EXPIRE_MESSAGE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[5]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CONFIRM_PIN_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_PIN0 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name='0']");
    private static final OneAppElement PB1_CARDLESS_PIN1 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name='1']");
    private static final OneAppElement PB1_CARDLESS_PIN2 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='btn1'][2]");
    private static final OneAppElement PB1_CARDLESS_PIN3 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='btn1'][3]");
    private static final OneAppElement PB1_CARDLESS_CODE_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CODE_PIN_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[3]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CODE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[4]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CODE_TIMER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[5]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CODE_SUBHEADER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[6]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_WITHDRAW_FROM = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[7]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_ACCOUNT_TYPE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[8]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_AMOUNT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[9]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_AMOUNT_NO = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[10]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_GENERATE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[11]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_GENERATE_TIME = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[12]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_EXPIRY = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[13]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_EXPIRY_TIME = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[14]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_CODE_DONE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeButton");
    private static final OneAppElement PB1_CARDLESS_CODE_DEACTIVE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeButton[2]");
    private static final OneAppElement PB1_CARDLESS_PIN_EXPIRE_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[15]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_PIN_EXPIRE_TITLE_HOME = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[15]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_PIN_CANCEL = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeButton[5]");
    private static final OneAppElement PB1_CARDLESS_PIN_OK = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeButton[4]");
    private static final OneAppElement PB1_CARDLESS_DEACTIVE_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[3]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_DEACTIVE_MESSAGE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[4]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_CARDLESS_DEACTIVE_DONE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeButton");
    private static final OneAppElement PB1_CARDLESS_DEACTIVE_GENERATE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeButton[2]");

    private static final OneAppElement PB1_EKYC_REGISTER_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_REGISTER_METHOD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_OPEN_AC = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_OPEN_AC_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeButton");
    private static final OneAppElement PB1_EKYC_OPEN_AC_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[3]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_ALLFREE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[4]/XCUIElementTypeOther");
    private static final OneAppElement PB1_EKYC_NOFIX = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[5]/XCUIElementTypeOther");
    private static final OneAppElement PB1_EKYC_SELECTAC_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='ekyc-product-list-button']");
    private static final OneAppElement PB1_EKYC_PRODUCT_IMG_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='ekyc-product-brief-button']");
    private static final OneAppElement PB1_EKYC_WIFIOFF_MESSAGE1 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[14]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_CHECKMOBILE_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='ekyc-mobile-number-check-button']");
    private static final OneAppElement PB1_EKYC_WIFIOFF_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[15]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_WIFIOFF_MESSAGE2 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[17]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_WIFI_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeButton[3]");
    private static final OneAppElement PB1_EKYC_STEP_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[4]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_TC_ACCEPT1 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[6]/XCUIElementTypeOther");
    private static final OneAppElement PB1_EKYC_TC_ACCEPT2 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[8]/XCUIElementTypeOther");
    private static final OneAppElement PB1_EKYC_TC_ACCEPT3 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[10]/XCUIElementTypeOther");
    private static final OneAppElement PB1_EKYC_TC_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='ekyc-terms-condition-button']");
    private static final OneAppElement PB1_EKYC_SCAN_TIPS = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[6]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_SCAN_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='ekyc-tips-to-scan-button']");
    private static final OneAppElement PB1_EKYC_SCAN_ALLOW = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther[3]");
    private static final OneAppElement PB1_EKYC_SCAN_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeButton[2]");
    private static final OneAppElement PB1_EKYC_PERSONAL_DETAILS = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[6]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_PERSONAL_ID = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ID number']");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[8]");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE_MR = new OneAppElement(FindBy.XPATH, "");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE_MISS = new OneAppElement(FindBy.XPATH, "");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE_MRS = new OneAppElement(FindBy.XPATH, "");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE_FIELD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypePicker");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE_PICKER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypePicker/XCUIElementTypePickerWheel");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE_DONE_EN = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='Done']");
    private static final OneAppElement PB1_EKYC_PERSONAL_TITLE_DONE_TH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='ถัดไป']");
    private static final OneAppElement PB1_EKYC_PERSONAL_FNAME_TH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeTextField[2]");
    private static final OneAppElement PB1_EKYC_PERSONAL_LNAME_TH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeTextField[3]");
    private static final OneAppElement PB1_EKYC_PERSONAL_FNAME_EN = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeTextField[4]");
    private static final OneAppElement PB1_EKYC_PERSONAL_LNAME_EN = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeTextField[5]");
    private static final OneAppElement PB1_EKYC_PERSONAL_DOB = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='Date of birth']");
    private static final OneAppElement PB1_EKYC_PERSONAL_CID_ISSUE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeTextField[7]");
    private static final OneAppElement PB1_EKYC_PERSONAL_CID_EXPIRY = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeTextField[8]");
    private static final OneAppElement PB1_EKYC_PERSONAL_CID_NONEXP = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='personal-details-field-checkbox']/XCUIElementTypeOther/XCUIElementTypeOther");
    private static final OneAppElement PB1_EKYC_PERSONAL_YEAR_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeNavigationBar[@name='WKDateTimeContextMenuView']/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_PERSONAL_YEAR_SELECT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='Show year picker']");
    private static final OneAppElement PB1_EKYC_PERSONAL_YEAR_SELECT1 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='Hide year picker']");
    private static final OneAppElement PB1_EKYC_PERSONAL_YEAR_FIELD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeDatePicker/XCUIElementTypePicker/XCUIElementTypePickerWheel[2]");
    private static final OneAppElement PB1_EKYC_PERSONAL_DATE_SELECT = new OneAppElement(FindBy.XPATH, "");
    private static final OneAppElement PB1_EKYC_PERSONAL_MONTH_FIELD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeDatePicker/XCUIElementTypePicker/XCUIElementTypePickerWheel[1]");
    private static final OneAppElement PB1_EKYC_PERSONAL_MONTH_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='Next Month']");
    private static final OneAppElement PB1_EKYC_PERSONAL_MONTH_PREVIOUS = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='Previous Month']");
    private static final OneAppElement PB1_EKYC_PERSONAL_DATE_SET = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeToolbar[@name='Toolbar']/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeButton[2]");
    private static final OneAppElement PB1_EKYC_PERSONAL_LASER_CODE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeTextField[9]");
    private static final OneAppElement PB1_EKYC_PERSONAL_CONFIRM = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeButton");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_ANSWER1 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[8]");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_ANSWER2 = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[11]");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_ANSWER_YES = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[12]");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_NEXT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='ekyc-fatca-button']");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_FAIL_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[3]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_FAIL_MESSAGE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeOther[@name='ONEAPP']/XCUIElementTypeOther[4]/XCUIElementTypeStaticText");
    private static final OneAppElement PB1_EKYC_PERSONAL_FATCA_FAIL_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name='ekyc-fatca-error-button']");

    
    public static void init(Map<String, OneAppElement> oneAppElementHashMap) {
        //PB 1
    	oneAppElementHashMap.put(OneAppElementKeys.PB1_HOME, PB1_HOME);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACCOUNT, PB1_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_MORE, PB1_MORE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_SETTING, PB1_SETTING);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_SETTING_BACK, PB1_SETTING_BACK);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_PERSONAL_INFORMATION, PB1_PERSONAL_INFORMATION);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_LANGUAGE, PB1_LANGUAGE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_LANGUAGE_TH, PB1_LANGUAGE_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_LANGUAGE_EN, PB1_LANGUAGE_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_LANGUAGE_BACK, PB1_LANGUAGE_BACK);
        
        oneAppElementHashMap.put(OneAppElementKeys.PB1_KEYPAD_DONE_EN, PB1_KEYPAD_DONE_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_KEYPAD_DONE_TH, PB1_KEYPAD_DONE_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_KEYPAD_ALLOW, PB1_KEYPAD_ALLOW);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_WITHDRAW, PB1_WITHDRAW);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_REGISTER_TTB, PB1_REGISTER_TTB);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACCEPT_T_AND_C, PB1_ACCEPT_T_AND_C);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_T_AND_C_NEXT, PB1_T_AND_C_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_INPUT_CID, PB1_INPUT_CID);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ENTER_CID_NEXT, PB1_ENTER_CID_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ENTER_PIN_TITLE, PB1_ENTER_PIN_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_OTP_HEADER, PB1_OTP_HEADER);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_OTP_REF, PB1_OTP_REF);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACTIVATE_NEXT_EN, PB1_ACTIVATE_NEXT_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACTIVATE_NEXT_TH, PB1_ACTIVATE_NEXT_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_HOME_INTRO_NEXT, PB1_HOME_INTRO_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACCOUNT_INTRO_NEXT, PB1_ACCOUNT_INTRO_NEXT);

        oneAppElementHashMap.put(OneAppElementKeys.PB1_DEPOSIT_ACCOUNT_LIST, PB1_DEPOSIT_ACCOUNT_LIST);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_ACCOUNT_NICKNAME, PB1_ACCOUNT_NICKNAME);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_MORE_MENU, PB1_MORE_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_MENU_TITLE, PB1_MENU_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_WITHDRAW, PB1_CARDLESS_WITHDRAW);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_TITLE, PB1_CARDLESS_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_AC_TYPE, PB1_CARDLESS_AC_TYPE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_FROM_AC, PB1_CARDLESS_FROM_AC);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_BALANCE, PB1_CARDLESS_BALANCE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_AMOUNT_FIELD, PB1_CARDLESS_AMOUNT_FIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_FIELD_HELP_TEXT, PB1_CARDLESS_FIELD_HELP_TEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_FIELD_HELP_TEXT1, PB1_CARDLESS_FIELD_HELP_TEXT1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_AC_TYPEA, PB1_CARDLESS_AC_TYPEA);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_FROM_ACA, PB1_CARDLESS_FROM_ACA);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_BALANCEA, PB1_CARDLESS_BALANCEA);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_FIELD_HELP_TEXTA, PB1_CARDLESS_FIELD_HELP_TEXTA);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_FIELD_HELP_TEXT1A, PB1_CARDLESS_FIELD_HELP_TEXT1A);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_BACK_BUTTON, PB1_CARDLESS_BACK_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT100, PB1_CARDLESS_SELECT_AMOUNT100);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT300, PB1_CARDLESS_SELECT_AMOUNT300);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT500, PB1_CARDLESS_SELECT_AMOUNT500);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT900, PB1_CARDLESS_SELECT_AMOUNT900);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT1000, PB1_CARDLESS_SELECT_AMOUNT1000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT2000, PB1_CARDLESS_SELECT_AMOUNT2000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT900, PB1_CARDLESS_SELECT_AMOUNT900);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT1000, PB1_CARDLESS_SELECT_AMOUNT1000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT2000, PB1_CARDLESS_SELECT_AMOUNT2000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT3000, PB1_CARDLESS_SELECT_AMOUNT3000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT4000, PB1_CARDLESS_SELECT_AMOUNT4000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_SELECT_AMOUNT5000, PB1_CARDLESS_SELECT_AMOUNT5000);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_NEXT, PB1_CARDLESS_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_TITLE, PB1_CARDLESS_CONFIRM_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_WITHDRAW_TITLE, PB1_CARDLESS_CONFIRM_WITHDRAW_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_AC_TYPE, PB1_CARDLESS_CONFIRM_AC_TYPE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_FROM, PB1_CARDLESS_CONFIRM_FROM);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_AMOUNT_TITLE, PB1_CARDLESS_CONFIRM_AMOUNT_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_AMOUNT, PB1_CARDLESS_CONFIRM_AMOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_BANNER1, PB1_CARDLESS_CONFIRM_BANNER1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_BANNER2, PB1_CARDLESS_CONFIRM_BANNER2);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_GENERATE, PB1_CARDLESS_CONFIRM_GENERATE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_BACK, PB1_CARDLESS_CONFIRM_BACK);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_EXPIRE_MESSAGE, PB1_CARDLESS_EXPIRE_MESSAGE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CONFIRM_PIN_TITLE, PB1_CARDLESS_CONFIRM_PIN_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN0, PB1_CARDLESS_PIN0);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN1, PB1_CARDLESS_PIN1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN2, PB1_CARDLESS_PIN2);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN3, PB1_CARDLESS_PIN3);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_TITLE, PB1_CARDLESS_CODE_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_PIN_TITLE, PB1_CARDLESS_CODE_PIN_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE, PB1_CARDLESS_CODE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_TIMER, PB1_CARDLESS_CODE_TIMER);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_SUBHEADER, PB1_CARDLESS_CODE_SUBHEADER);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_WITHDRAW_FROM, PB1_CARDLESS_WITHDRAW_FROM);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_ACCOUNT_TYPE, PB1_CARDLESS_ACCOUNT_TYPE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_AMOUNT, PB1_CARDLESS_AMOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_AMOUNT_NO, PB1_CARDLESS_AMOUNT_NO);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_GENERATE, PB1_CARDLESS_GENERATE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_GENERATE_TIME, PB1_CARDLESS_GENERATE_TIME);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_EXPIRY, PB1_CARDLESS_EXPIRY);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_EXPIRY_TIME, PB1_CARDLESS_EXPIRY_TIME);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_DONE, PB1_CARDLESS_CODE_DONE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_CODE_DEACTIVE, PB1_CARDLESS_CODE_DEACTIVE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN_EXPIRE_TITLE, PB1_CARDLESS_PIN_EXPIRE_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN_EXPIRE_TITLE_HOME, PB1_CARDLESS_PIN_EXPIRE_TITLE_HOME);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN_CANCEL, PB1_CARDLESS_PIN_CANCEL);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_PIN_OK, PB1_CARDLESS_PIN_OK);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_DEACTIVE_TITLE, PB1_CARDLESS_DEACTIVE_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_DEACTIVE_MESSAGE, PB1_CARDLESS_DEACTIVE_MESSAGE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_DEACTIVE_DONE, PB1_CARDLESS_DEACTIVE_DONE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_CARDLESS_DEACTIVE_GENERATE, PB1_CARDLESS_DEACTIVE_GENERATE);

        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_REGISTER_TITLE, PB1_EKYC_REGISTER_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_REGISTER_METHOD, PB1_EKYC_REGISTER_METHOD);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_OPEN_AC, PB1_EKYC_OPEN_AC);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_OPEN_AC_NEXT, PB1_EKYC_OPEN_AC_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_OPEN_AC_TITLE, PB1_EKYC_OPEN_AC_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_ALLFREE, PB1_EKYC_ALLFREE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_NOFIX, PB1_EKYC_NOFIX);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_SELECTAC_NEXT, PB1_EKYC_SELECTAC_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PRODUCT_IMG_NEXT, PB1_EKYC_PRODUCT_IMG_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_WIFIOFF_MESSAGE1, PB1_EKYC_WIFIOFF_MESSAGE1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_CHECKMOBILE_NEXT, PB1_EKYC_CHECKMOBILE_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_WIFIOFF_TITLE, PB1_EKYC_WIFIOFF_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_WIFIOFF_MESSAGE2, PB1_EKYC_WIFIOFF_MESSAGE2);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_WIFI_NEXT, PB1_EKYC_WIFI_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_STEP_TITLE, PB1_EKYC_STEP_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_TC_ACCEPT1, PB1_EKYC_TC_ACCEPT1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_TC_ACCEPT2, PB1_EKYC_TC_ACCEPT2);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_TC_ACCEPT3, PB1_EKYC_TC_ACCEPT3);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_TC_NEXT, PB1_EKYC_TC_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_SCAN_TIPS, PB1_EKYC_SCAN_TIPS);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_SCAN_NEXT, PB1_EKYC_SCAN_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_SCAN_ALLOW, PB1_EKYC_SCAN_ALLOW);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_SCAN_BUTTON, PB1_EKYC_SCAN_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_DETAILS, PB1_EKYC_PERSONAL_DETAILS);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_ID, PB1_EKYC_PERSONAL_ID);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE, PB1_EKYC_PERSONAL_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE_MR, PB1_EKYC_PERSONAL_TITLE_MR);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE_MISS, PB1_EKYC_PERSONAL_TITLE_MISS);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE_MRS, PB1_EKYC_PERSONAL_TITLE_MRS);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE_FIELD, PB1_EKYC_PERSONAL_TITLE_FIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE_PICKER, PB1_EKYC_PERSONAL_TITLE_PICKER);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE_DONE_EN, PB1_EKYC_PERSONAL_TITLE_DONE_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_TITLE_DONE_TH, PB1_EKYC_PERSONAL_TITLE_DONE_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FNAME_TH, PB1_EKYC_PERSONAL_FNAME_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_LNAME_TH, PB1_EKYC_PERSONAL_LNAME_TH);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FNAME_EN, PB1_EKYC_PERSONAL_FNAME_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_LNAME_EN, PB1_EKYC_PERSONAL_LNAME_EN);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_DOB, PB1_EKYC_PERSONAL_DOB);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_CID_ISSUE, PB1_EKYC_PERSONAL_CID_ISSUE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_CID_EXPIRY, PB1_EKYC_PERSONAL_CID_EXPIRY);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_CID_NONEXP, PB1_EKYC_PERSONAL_CID_NONEXP);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_YEAR_TITLE, PB1_EKYC_PERSONAL_YEAR_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_YEAR_SELECT, PB1_EKYC_PERSONAL_YEAR_SELECT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_YEAR_SELECT1, PB1_EKYC_PERSONAL_YEAR_SELECT1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_YEAR_FIELD, PB1_EKYC_PERSONAL_YEAR_FIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_DATE_SELECT, PB1_EKYC_PERSONAL_DATE_SELECT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_MONTH_FIELD, PB1_EKYC_PERSONAL_MONTH_FIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_MONTH_NEXT, PB1_EKYC_PERSONAL_MONTH_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_MONTH_PREVIOUS, PB1_EKYC_PERSONAL_MONTH_PREVIOUS);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_DATE_SET, PB1_EKYC_PERSONAL_DATE_SET);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_LASER_CODE, PB1_EKYC_PERSONAL_LASER_CODE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_CONFIRM, PB1_EKYC_PERSONAL_CONFIRM);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_ANSWER1, PB1_EKYC_PERSONAL_FATCA_ANSWER1);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_ANSWER2, PB1_EKYC_PERSONAL_FATCA_ANSWER2);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_ANSWER_YES, PB1_EKYC_PERSONAL_FATCA_ANSWER_YES);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_NEXT, PB1_EKYC_PERSONAL_FATCA_NEXT);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_FAIL_TITLE, PB1_EKYC_PERSONAL_FATCA_FAIL_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_FAIL_MESSAGE, PB1_EKYC_PERSONAL_FATCA_FAIL_MESSAGE);
        oneAppElementHashMap.put(OneAppElementKeys.PB1_EKYC_PERSONAL_FATCA_FAIL_BUTTON, PB1_EKYC_PERSONAL_FATCA_FAIL_BUTTON);


    }
}

