package com.ttbbank.oneapp.framework.element.ios;

import com.ttbbank.oneapp.framework.FindBy;
import com.ttbbank.oneapp.framework.OneAppElement;
import com.ttbbank.oneapp.framework.OneAppElementKeys;
import io.appium.java_client.FindsByIosClassChain;

import java.util.Map;

public class Pb3iOSOneAppElements {
    private Pb3iOSOneAppElements() {

    }

    //Primary banking 3
    private static final OneAppElement PB3_TITLE_TRANSFER_LANDING = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Transfer\"]");
    private static final OneAppElement PB3_TRANSFER_OWN_MENU = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Own ttb account\"]");
    private static final OneAppElement PB3_TRANSFER_OTHER_MENU = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Other Accounts\"]");
    private static final OneAppElement PB3_TRANSFER_PROMPT_PAY_MENU = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Promptpay\"]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_TRANSFER_SUCCESSFULLY = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Transfer Successful\"]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_FROM_ACCOUNT_NAME = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"นาย ไนซ์ เดฟไอโอเอส\"]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_FROM_ACCOUNT_NUMBER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"045-7-76198-9\"]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_FROM_ACCOUNT_BANK_SHORT_NAME = new OneAppElement(FindBy.XPATH, "(//XCUIElementTypeStaticText[@name=\"ttb\"])[1]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_TO_ACCOUNT_NAME = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"นาย ไนซ์ เดฟไอโอเอส .\"]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_TO_ACCOUNT_NUMBER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"357-2-07755-4\"]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_TO_ACCOUNT_BANK_SHORT_NAME = new OneAppElement(FindBy.XPATH, "(//XCUIElementTypeStaticText[@name=\"ttb\"])[2]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_AMOUNT_VALUE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "1,000.00");
    private static final OneAppElement PB3_PROMPTPAY_MOBILE_COMPLETE_AMOUNT_VALUE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "99.00");
    private static final OneAppElement PB3_PROMPTPAY_CRITIZEN_COMPLETE_AMOUNT_VALUE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "1,111.00");
    private static final OneAppElement PB3_ONEHUNDRED_ONE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "101.00");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_FEE_VALUE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"0.00\"]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_NOTE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Note: Noted");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_CATEGORY = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Category: Savings & Investment");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_CATEGORY_FOOD = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Category: Food & Drinks");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_REMAINING_BALANCE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Remaining Balance: 8,736.09\"]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_DONE_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Done \"]");
    private static final OneAppElement PB3_TRANSFER_COMPLETE_BACK_TO_HOME = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Back to Home\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_FROM_ACCOUNT_NUMBER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"001-7-31461-8\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_SELECT_TO_ACCOUNT_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name=\"ChevronDown\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_TO_ACCOUNT_BOTTOM_SHEET_EXIT_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name=\"px close\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_TO_ACCOUNT_BOTTOM_SHEET_SELECTED_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[1]");
    private static final OneAppElement PB3_ENTER_DETAILS_TO_ACCOUNT_NUMBER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"019-2-01068-4\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_AMOUNT_TEXT_FIELD_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB3_ENTER_DETAILS_KEYBOARD_NUMBER_ONE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"1\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_KEYBOARD_NUMBER_TWO = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"2\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_KEYBOARD_NUMBER_THREE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"3\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_KEYBOARD_NUMBER_FOUR = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"4\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_KEYBOARD_NUMBER_FIVE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"5\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_KEYBOARD_NUMBER_SIX = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"6\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_KEYBOARD_NUMBER_SEVEN = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"7\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_KEYBOARD_NUMBER_EIGHT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"8\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_KEYBOARD_NUMBER_NINE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"9\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_KEYBOARD_NUMBER_ZERO = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"0\"]");
    private static final OneAppElement PB3_KEYPAD_DONE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@label='Done']");
    private static final OneAppElement PB3_ENTER_DETAILS_CATEGORY_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name=\"Savings & Investment\"]");
    private static final OneAppElement PB3_ENTER_DETAILS_NEXT_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name=\"Next\"]");
    private static final OneAppElement PB3_TRANSFER_REVIEW_FROM_ACCOUNT_NUMBER = new OneAppElement(FindBy.ACCESSIBILITY_ID, "045-7-76198-9");
    private static final OneAppElement PB3_TRANSFER_REVIEW_TO_ACCOUNT_NUMBER = new OneAppElement(FindBy.ACCESSIBILITY_ID, "357-2-07755-4");
    private static final OneAppElement PB3_PROMPTPAY_MOBILE_REVIEW_FROM_ACCOUNT_NUMBER = new OneAppElement(FindBy.ACCESSIBILITY_ID, "001-7-31461-8");
    private static final OneAppElement PB3_PROMPTPAY_MOBILE_REVIEW_TO_ACCOUNT_NUMBER = new OneAppElement(FindBy.ACCESSIBILITY_ID, "080-602-3914");
    private static final OneAppElement PB3_PROMPTPAY_CITIZEN_REVIEW_TO_ACCOUNT_NUMBER_XPATH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"1-2850-58642-53-7\"]");
    private static final OneAppElement PB3_PROMPTPAY_CITIZEN_REVIEW_TO_ACCOUNT_NUMBER = new OneAppElement(FindBy.ACCESSIBILITY_ID, "1-2850-58642-53-7");
    private static final OneAppElement PB3_PROMPTPAY_MOBILE_REVIEW_AMOUNT = new OneAppElement(FindBy.ACCESSIBILITY_ID, "99.00");
    private static final OneAppElement PB3_TRANSFER_REVIEW_AMOUNT = new OneAppElement(FindBy.ACCESSIBILITY_ID, "1,000.00");
    private static final OneAppElement PB3_TRANSFER_REVIEW_NOTE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Noted");
    private static final OneAppElement PB3_TRANSFER_REVIEW_CATEGORY = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Savings & Investment");
    private static final OneAppElement PB3_TRANSFER_REVIEW_CATEGORY_FOOD = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Food & Drinks");
    private static final OneAppElement PB3_COMPLETE_DONE_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Done\"]");
    private static final OneAppElement PB3_TRANSFER_REVIEW_CONFIRM_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name=\"Confirm\"]");
    private static final OneAppElement PB3_TRANSFER_REVIEW_CONFIRM = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Confirm\"]");
    private static final OneAppElement PB3_TRANSFER_ENTER_DETAILS_EMOJI_UD83D = new OneAppElement(FindBy.XPATH, "(//XCUIElementTypeStaticText[@name=\"\uD83D\uDE02\"])[1]");
    private static final OneAppElement PB3_TRANSFER_ENTER_DETAILS_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Transfer\"]");
    private static final OneAppElement PB3_TRANSFER_ENTER_DETAILS_NOTE_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Note (Optional)\"]");
    private static final OneAppElement PB3_KEYPAD_N = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"N\"]");
    private static final OneAppElement PB3_KEYPAD_O = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"O\"]");
    private static final OneAppElement PB3_KEYPAD_T = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"T\"]");
    private static final OneAppElement PB3_KEYPAD_E = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"E\"]");
    private static final OneAppElement PB3_KEYPAD_D = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"D\"]");
    private static final OneAppElement PB3_KEYPAD_O_SMALL = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"o\"]");
    private static final OneAppElement PB3_KEYPAD_T_SMALL = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"t\"]");
    private static final OneAppElement PB3_KEYPAD_E_SMALL = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"e\"]");
    private static final OneAppElement PB3_KEYPAD_D_SMALL = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeKey[@name=\"d\"]");
    private static final OneAppElement PB3_TRANSFER_REVIEW_TITLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Review Transfer Details\"]");
    private static final OneAppElement PB3_KEYPAD_EMOJI_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name=\"Emoji\"]");
    private static final OneAppElement PB3_ENTER_DETAIL_ERROR_INSUFFICIENT_FOUNDS = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Your account has insufficient funds for this transaction.");
    private static final OneAppElement PB3_ENTER_DETAIL_ERROR_NO_SELECTED_TO_ACCOUNT = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Please select destination account.");
    private static final OneAppElement PB3_ENTER_DETAIL_ERROR_NO_FILLED_AMOUNT = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Please enter an amount.");
    private static final OneAppElement PB3_ENTER_DETAIL_TO_ACCOUNT_BOTTOM_SHEET_CLOSE_ICON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeButton[@name=\"px close\"]");
    private static final OneAppElement PB3_LANDING_PROMPTPAY_MENU = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Promptpay");
    private static final OneAppElement PB3_ENTER_DETAIL_PROMPTPAY_TITLE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Transfer");
    private static final OneAppElement PB3_ENTER_DETAIL_PROMPTPAY_FROM_ACCOUNT_NUMBER = new OneAppElement(FindBy.ACCESSIBILITY_ID, "001-7-31461-8");
    private static final OneAppElement PB3_ENTER_DETAIL_PROMPTPAY_TO_ACCOUNT_NUMBER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB3_ENTER_DETAIL_PROMPTPAY_AMOUNT_TEXT_FIELD = new OneAppElement(FindBy.ACCESSIBILITY_ID, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB3_ENTER_DETAIL_PROMPTPAY_CATEGORY = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Savings & Investment\"]");
    private static final OneAppElement PB3_ENTER_DETAIL_PROMPTPAY_CATEGORY_FOOD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Food & Drinks\"]");
    private static final OneAppElement PB3_OTHER_TRANSFER_MENU = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Other Accounts");
    private static final OneAppElement PB3_OTHER_TRANSFER_SELECT_BANK_MENU = new OneAppElement(FindBy.ACCESSIBILITY_ID, "ChevronDown");
    private static final OneAppElement PB3_OTHER_TRANSFER_SELECT_BANK_TTB = new OneAppElement(FindBy.ACCESSIBILITY_ID, "ttb");
    private static final OneAppElement PB3_OTHER_TRANSFER_SELECT_BANK_SCB = new OneAppElement(FindBy.ACCESSIBILITY_ID, "SCB");
    private static final OneAppElement PB3_OTHER_TRANSFER_OWN_ACCOUNT_NAME = new OneAppElement(FindBy.ACCESSIBILITY_ID, "basic account");
    private static final OneAppElement PB3_OTHER_TRANSFER_OWN_ACCOUNT_NAME_TEXTFIELD = new OneAppElement(FindBy.XPATH, "(//XCUIElementTypeStaticText[@name=\"basic account\"])[2]");
    private static final OneAppElement PB3_OTHER_TRANSFER_TO_ACCOUNT_TEXTFIELD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB3_OTHER_TRANSFER_XPATH_TTB = new OneAppElement(FindBy.XPATH, "(//XCUIElementTypeStaticText[@name=\"ttb\"])[2]");
    private static final OneAppElement PB3_OTHER_TRANSFER_OTHER_ACCOUNT_NUMBER = new OneAppElement(FindBy.ACCESSIBILITY_ID, "045-7-76198-9");
    private static final OneAppElement PB3_OTHER_TRANSFER_OWN_ACCOUNT_NUMBER = new OneAppElement(FindBy.ACCESSIBILITY_ID, "019-2-01068-4");
    private static final OneAppElement PB3_OTHER_TRANSFER_BANK_SCB = new OneAppElement(FindBy.ACCESSIBILITY_ID, "SCB");
    private static final OneAppElement PB3_OTHER_TRANSFER_OTHER_BANK_ACCOUNT = new OneAppElement(FindBy.ACCESSIBILITY_ID, "111-3-92689-0");
    private static final OneAppElement PB3_OTHER_TRANSFER_AMOUNT_TEXT_FIELD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB3_OTHER_TRANSFER_AMOUNT_TEXT_FIELD_WITHOUT_DAILYLIMIT = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[5]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB3_OTHER_ENTER_DETAILS_TO_ACCOUNT_NUMBER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"045-7-76198-9\"]");
    private static final OneAppElement PB3_OTHER_BANK_ENTER_DETAILS_TO_ACCOUNT_NUMBER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"111-3-92689-0\"]");
    private static final OneAppElement PB3_OTHER_TTB_ACCOUNT_NUMBER_TEXTFIELD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB3_KEY_BOARD_A_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "a");
    private static final OneAppElement PB3_KEY_BOARD_B_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "b");
    private static final OneAppElement PB3_KEY_BOARD_C_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "c");
    private static final OneAppElement PB3_KEY_BOARD_D_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "d");
    private static final OneAppElement PB3_KEY_BOARD_E_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "e");
    private static final OneAppElement PB3_KEY_BOARD_F_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "f");
    private static final OneAppElement PB3_KEY_BOARD_G_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "g");
    private static final OneAppElement PB3_KEY_BOARD_H_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "h");
    private static final OneAppElement PB3_KEY_BOARD_I_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "i");
    private static final OneAppElement PB3_KEY_BOARD_J_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "j");
    private static final OneAppElement PB3_KEY_BOARD_K_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "k");
    private static final OneAppElement PB3_KEY_BOARD_L_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "l");
    private static final OneAppElement PB3_KEY_BOARD_M_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "m");
    private static final OneAppElement PB3_KEY_BOARD_N_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "n");
    private static final OneAppElement PB3_KEY_BOARD_O_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "o");
    private static final OneAppElement PB3_KEY_BOARD_P_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "p");
    private static final OneAppElement PB3_KEY_BOARD_Q_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "q");
    private static final OneAppElement PB3_KEY_BOARD_R_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "r");
    private static final OneAppElement PB3_KEY_BOARD_S_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "s");
    private static final OneAppElement PB3_KEY_BOARD_T_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "t");
    private static final OneAppElement PB3_KEY_BOARD_U_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "u");
    private static final OneAppElement PB3_KEY_BOARD_V_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "v");
    private static final OneAppElement PB3_KEY_BOARD_W_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "w");
    private static final OneAppElement PB3_KEY_BOARD_X_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "x");
    private static final OneAppElement PB3_KEY_BOARD_Y_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "y");
    private static final OneAppElement PB3_KEY_BOARD_Z_BUTTON = new OneAppElement(FindBy.ACCESSIBILITY_ID, "z");
    private static final OneAppElement PB3_SET_SCHEDULE_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeSwitch");
    private static final OneAppElement PB3_SET_SCHEDULE_NAME_TEXTFIELD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB3_SET_SCHEDULE_STARTDATE_TEXTFIELD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeTextField");
    private static final OneAppElement PB3_ADD_SCHEDULE_BUTTON = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Add Schedule\"]");
    private static final OneAppElement PB3_REVIEW_TITLE_SCHEDULE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeStaticText[@name=\"Review Schedule\"]");
    private static final OneAppElement PB3_REVIEW_SCHEDULE_AMOUNT = new OneAppElement(FindBy.ACCESSIBILITY_ID, "1.00");
    private static final OneAppElement PB3_REVIEW_SCHEDULE_FEE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "0.00");
    private static final OneAppElement PB3_REVIEW_SCHEDULE_FREQUENCY_ONCE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Once");
    private static final OneAppElement PB3_TRANSFER_REVIEW_FROM_ACCOUNT_NUMBER_KAI = new OneAppElement(FindBy.ACCESSIBILITY_ID, "001-7-31461-8");
    private static final OneAppElement PB3_TRANSFER_REVIEW_TO_ACCOUNT_NUMBER_KAI = new OneAppElement(FindBy.ACCESSIBILITY_ID, "019-2-01068-4");
    private static final OneAppElement PB3_SCHEDULE_COMPLETE_TITLE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Schedule is Successfully Created");
    private static final OneAppElement PB3_SCHEDULE_FREQUENCY_WEEKLY_RADIO = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Weekly");
    private static final OneAppElement PB3_SCHEDULE_FREQUENCY_ENDDATE_TEXTFIELD = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeTextField");
    private static final OneAppElement PB3_SCHEDULE_FREQUENCY_AMOUNTOFTIMES_TEXTFIELD = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Amount of times text field");
    private static final OneAppElement PB3_SCHEDULE_FREQUENCY_AMOUNTOFTIMES_RADIO = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Amount of times");
    private static final OneAppElement PB3_SCHEDULE_FREQUENCY_DAY_EVERY = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeTextField[2]");
    private static final OneAppElement PB3_SCHEDULE_MONTHLY_NOTE = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Note: In case a month does not contain your chosen date, your transaction will be completed at the end of that month");
    private static final OneAppElement PB3_SCHEDULE_RADIO_MONTHLY = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Monthly");
    private static final OneAppElement PB3_SCHEDULE_END_DATE_TEXTFIELD_MONTHLY = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[4]/XCUIElementTypeTextField");
    private static final OneAppElement PB3_SCHEDULE_AMOUNE_OF_TIMES_TEXTFIELD_MONTHLY = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Amount of times text field");
    private static final OneAppElement PB3_SET_SCHEDULE_BUTTON_WITH_OTHER_OWN_XPATH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[6]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeSwitch");
    private static final OneAppElement PB3_SET_SCHEDULE_NAME_TEXTFIELD_WITH_OTHER_OWN_XPATH = new OneAppElement(FindBy.XPATH,"//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[7]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB3_SET_SCHEDULE_START_DATE_TEXTFIELD_WITH_OTHER_OWN_XPATH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[7]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeTextField");
    private static final OneAppElement PB3_SET_SCHEDULE_END_DATE_TEXTFIELD_WITH_OTHER_OWN_XPATH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[7]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeTextField");
    private static final OneAppElement PB3_SET_SCHEDULE_EVERY_DATE_WITH_OTHER_OWN_XPATH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[7]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeTextField[2]");
    private static final OneAppElement PB3_SET_SCHEDULE_AMOUNT_OF_TIMES_TEXTFIELD_WITH_OTHER_OWN_XPATH = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Amount of times text field");
    private static final OneAppElement PB3_SET_SCHEDULE_END_DATE_MONTHLY_WITH_OTHER_OWN_XPATH = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[7]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[4]/XCUIElementTypeTextField");
    private static final OneAppElement PB3_SET_SCHEDULE_AMOUNT_OF_TIMES_MONTHLY_WITH_OTHER_OWN_XPATH = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Amount of times text field");
    private static final OneAppElement PB3_SCHEDULE_ERROR_AMOUNT_OF_TIME = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Time must be from 1 to 999.");
    private static final OneAppElement PB3_MESSAGE_ERROR_SCHEDULE_NAME_PLEASE_ENTER = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Please enter a schedule name");
    private static final OneAppElement PB3_MESSAGE_ERROR_SCHEDULE_NAME_MUST_BE_BETWEEN = new OneAppElement(FindBy.ACCESSIBILITY_ID, "Must be between 3-70 Characters.");
    private static final OneAppElement PB3_SET_SCHEDULE_TOGGLE = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[5]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeSwitch");
    private static final OneAppElement PB3_SET_SCHEDULE_NAME_OTHER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[6]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField");
    private static final OneAppElement PB3_SET_SCHEDULE_START_DATE_OTHER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[6]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeTextField");
    private static final OneAppElement PB3_SET_SCHEDULE_EVERY_DATE_OTHER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[6]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeTextField[2]");
    private static final OneAppElement PB3_SET_SCHEDULE_END_DATE_OTHER = new OneAppElement(FindBy.XPATH, "//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[6]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[4]/XCUIElementTypeTextField");
    private static final OneAppElement PB3_SET_SCHEDULE_END_DATE_MONTHLY_OTHER = new OneAppElement(FindBy.XPATH,"//XCUIElementTypeApplication[@name=\"OneApp\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[6]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[5]/XCUIElementTypeTextField");

    public static void init(Map<String, OneAppElement> oneAppElementHashMap) {
        //PB3
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_TOGGLE, PB3_SET_SCHEDULE_TOGGLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_NAME_OTHER, PB3_SET_SCHEDULE_NAME_OTHER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_START_DATE_OTHER, PB3_SET_SCHEDULE_START_DATE_OTHER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_EVERY_DATE_OTHER, PB3_SET_SCHEDULE_EVERY_DATE_OTHER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_END_DATE_OTHER, PB3_SET_SCHEDULE_END_DATE_OTHER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_END_DATE_MONTHLY_OTHER, PB3_SET_SCHEDULE_END_DATE_MONTHLY_OTHER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_END_DATE_MONTHLY_WITH_OTHER_OWN_XPATH, PB3_SET_SCHEDULE_END_DATE_MONTHLY_WITH_OTHER_OWN_XPATH);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_AMOUNT_OF_TIMES_MONTHLY_WITH_OTHER_OWN_XPATH, PB3_SET_SCHEDULE_AMOUNT_OF_TIMES_MONTHLY_WITH_OTHER_OWN_XPATH);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_AMOUNT_OF_TIMES_TEXTFIELD_WITH_OTHER_OWN_XPATH, PB3_SET_SCHEDULE_AMOUNT_OF_TIMES_TEXTFIELD_WITH_OTHER_OWN_XPATH);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_END_DATE_TEXTFIELD_WITH_OTHER_OWN_XPATH, PB3_SET_SCHEDULE_END_DATE_TEXTFIELD_WITH_OTHER_OWN_XPATH);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_EVERY_DATE_WITH_OTHER_OWN_XPATH, PB3_SET_SCHEDULE_EVERY_DATE_WITH_OTHER_OWN_XPATH);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_START_DATE_TEXTFIELD_WITH_OTHER_OWN_XPATH, PB3_SET_SCHEDULE_START_DATE_TEXTFIELD_WITH_OTHER_OWN_XPATH);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_NAME_TEXTFIELD_WITH_OTHER_OWN_XPATH, PB3_SET_SCHEDULE_NAME_TEXTFIELD_WITH_OTHER_OWN_XPATH);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_BUTTON_WITH_OTHER_OWN_XPATH, PB3_SET_SCHEDULE_BUTTON_WITH_OTHER_OWN_XPATH);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_END_DATE_TEXTFIELD_MONTHLY, PB3_SCHEDULE_END_DATE_TEXTFIELD_MONTHLY);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_AMOUNE_OF_TIMES_TEXTFIELD_MONTHLY, PB3_SCHEDULE_AMOUNE_OF_TIMES_TEXTFIELD_MONTHLY);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_FREQUENCY_DAY_EVERY, PB3_SCHEDULE_FREQUENCY_DAY_EVERY);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_FREQUENCY_WEEKLY_RADIO, PB3_SCHEDULE_FREQUENCY_WEEKLY_RADIO);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_FREQUENCY_ENDDATE_TEXTFIELD, PB3_SCHEDULE_FREQUENCY_ENDDATE_TEXTFIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_FREQUENCY_AMOUNTOFTIMES_TEXTFIELD, PB3_SCHEDULE_FREQUENCY_AMOUNTOFTIMES_TEXTFIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_FREQUENCY_AMOUNTOFTIMES_RADIO, PB3_SCHEDULE_FREQUENCY_AMOUNTOFTIMES_RADIO);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_COMPLETE_TITLE, PB3_SCHEDULE_COMPLETE_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_TO_ACCOUNT_NUMBER_KAI, PB3_TRANSFER_REVIEW_TO_ACCOUNT_NUMBER_KAI);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_FROM_ACCOUNT_NUMBER_KAI, PB3_TRANSFER_REVIEW_FROM_ACCOUNT_NUMBER_KAI);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_REVIEW_SCHEDULE_FEE, PB3_REVIEW_SCHEDULE_FEE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_REVIEW_SCHEDULE_FREQUENCY_ONCE, PB3_REVIEW_SCHEDULE_FREQUENCY_ONCE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_REVIEW_SCHEDULE_AMOUNT, PB3_REVIEW_SCHEDULE_AMOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TITLE_TRANSFER_LANDING, PB3_TITLE_TRANSFER_LANDING);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_OWN_MENU, PB3_TRANSFER_OWN_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_OTHER_MENU, PB3_TRANSFER_OTHER_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_PROMPT_PAY_MENU, PB3_TRANSFER_PROMPT_PAY_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_TRANSFER_SUCCESSFULLY, PB3_TRANSFER_COMPLETE_TRANSFER_SUCCESSFULLY);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_FROM_ACCOUNT_NAME, PB3_TRANSFER_COMPLETE_FROM_ACCOUNT_NAME);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_FROM_ACCOUNT_NUMBER, PB3_TRANSFER_COMPLETE_FROM_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_FROM_ACCOUNT_BANK_SHORT_NAME, PB3_TRANSFER_COMPLETE_FROM_ACCOUNT_BANK_SHORT_NAME);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_TO_ACCOUNT_NAME, PB3_TRANSFER_COMPLETE_TO_ACCOUNT_NAME);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_TO_ACCOUNT_NUMBER, PB3_TRANSFER_COMPLETE_TO_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_TO_ACCOUNT_BANK_SHORT_NAME, PB3_TRANSFER_COMPLETE_TO_ACCOUNT_BANK_SHORT_NAME);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_AMOUNT_VALUE, PB3_TRANSFER_COMPLETE_AMOUNT_VALUE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_FEE_VALUE, PB3_TRANSFER_COMPLETE_FEE_VALUE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_NOTE, PB3_TRANSFER_COMPLETE_NOTE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_CATEGORY, PB3_TRANSFER_COMPLETE_CATEGORY);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_REMAINING_BALANCE, PB3_TRANSFER_COMPLETE_REMAINING_BALANCE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_DONE_BUTTON, PB3_TRANSFER_COMPLETE_DONE_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_BACK_TO_HOME, PB3_TRANSFER_COMPLETE_BACK_TO_HOME);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_FROM_ACCOUNT_NUMBER, PB3_ENTER_DETAILS_FROM_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_SELECT_TO_ACCOUNT_BUTTON, PB3_ENTER_DETAILS_SELECT_TO_ACCOUNT_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_TO_ACCOUNT_BOTTOM_SHEET_EXIT_BUTTON, PB3_ENTER_DETAILS_TO_ACCOUNT_BOTTOM_SHEET_EXIT_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_TO_ACCOUNT_BOTTOM_SHEET_SELECTED_BUTTON, PB3_ENTER_DETAILS_TO_ACCOUNT_BOTTOM_SHEET_SELECTED_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_TO_ACCOUNT_NUMBER, PB3_ENTER_DETAILS_TO_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_AMOUNT_TEXT_FIELD_BUTTON, PB3_ENTER_DETAILS_AMOUNT_TEXT_FIELD_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_ZERO, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_ZERO);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_ONE, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_ONE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_TWO, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_TWO);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_THREE, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_THREE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_FOUR, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_FOUR);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_FIVE, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_FIVE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_SIX, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_SIX);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_SEVEN, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_SEVEN);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_EIGHT, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_EIGHT);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_NINE, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_NINE);

        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_DONE, PB3_KEYPAD_DONE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_CATEGORY_BUTTON, PB3_ENTER_DETAILS_CATEGORY_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_NEXT_BUTTON, PB3_ENTER_DETAILS_NEXT_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_FROM_ACCOUNT_NUMBER, PB3_TRANSFER_REVIEW_FROM_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_TO_ACCOUNT_NUMBER, PB3_TRANSFER_REVIEW_TO_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_AMOUNT, PB3_TRANSFER_REVIEW_AMOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_NOTE, PB3_TRANSFER_REVIEW_NOTE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_CATEGORY, PB3_TRANSFER_REVIEW_CATEGORY);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_CONFIRM_BUTTON, PB3_TRANSFER_REVIEW_CONFIRM_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_ENTER_DETAILS_EMOJI_UD83D, PB3_TRANSFER_ENTER_DETAILS_EMOJI_UD83D);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_ENTER_DETAILS_TITLE, PB3_TRANSFER_ENTER_DETAILS_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_ENTER_DETAILS_NOTE_BUTTON, PB3_TRANSFER_ENTER_DETAILS_NOTE_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_N, PB3_KEYPAD_N);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_O, PB3_KEYPAD_O);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_T, PB3_KEYPAD_T);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_E, PB3_KEYPAD_E);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_D, PB3_KEYPAD_D);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_TITLE, PB3_TRANSFER_REVIEW_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_EMOJI_BUTTON, PB3_KEYPAD_EMOJI_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_CONFIRM, PB3_TRANSFER_REVIEW_CONFIRM);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAIL_ERROR_INSUFFICIENT_FOUNDS, PB3_ENTER_DETAIL_ERROR_INSUFFICIENT_FOUNDS);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAIL_ERROR_NO_SELECTED_TO_ACCOUNT, PB3_ENTER_DETAIL_ERROR_NO_SELECTED_TO_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAIL_ERROR_NO_FILLED_AMOUNT, PB3_ENTER_DETAIL_ERROR_NO_FILLED_AMOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAILS_KEYBOARD_NUMBER_NINE, PB3_ENTER_DETAILS_KEYBOARD_NUMBER_NINE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAIL_TO_ACCOUNT_BOTTOM_SHEET_CLOSE_ICON, PB3_ENTER_DETAIL_TO_ACCOUNT_BOTTOM_SHEET_CLOSE_ICON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_LANDING_PROMPTPAY_MENU, PB3_LANDING_PROMPTPAY_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAIL_PROMPTPAY_TITLE, PB3_ENTER_DETAIL_PROMPTPAY_TITLE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAIL_PROMPTPAY_FROM_ACCOUNT_NUMBER, PB3_ENTER_DETAIL_PROMPTPAY_FROM_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAIL_PROMPTPAY_TO_ACCOUNT_NUMBER, PB3_ENTER_DETAIL_PROMPTPAY_TO_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAIL_PROMPTPAY_AMOUNT_TEXT_FIELD, PB3_ENTER_DETAIL_PROMPTPAY_AMOUNT_TEXT_FIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAIL_PROMPTPAY_CATEGORY, PB3_ENTER_DETAIL_PROMPTPAY_CATEGORY);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_PROMPTPAY_MOBILE_REVIEW_FROM_ACCOUNT_NUMBER, PB3_PROMPTPAY_MOBILE_REVIEW_FROM_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_PROMPTPAY_MOBILE_REVIEW_TO_ACCOUNT_NUMBER, PB3_PROMPTPAY_MOBILE_REVIEW_TO_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_PROMPTPAY_MOBILE_REVIEW_AMOUNT, PB3_PROMPTPAY_MOBILE_REVIEW_AMOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_PROMPTPAY_MOBILE_COMPLETE_AMOUNT_VALUE, PB3_PROMPTPAY_MOBILE_COMPLETE_AMOUNT_VALUE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_PROMPTPAY_CRITIZEN_COMPLETE_AMOUNT_VALUE, PB3_PROMPTPAY_CRITIZEN_COMPLETE_AMOUNT_VALUE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_COMPLETE_DONE_BUTTON, PB3_COMPLETE_DONE_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ENTER_DETAIL_PROMPTPAY_CATEGORY_FOOD, PB3_ENTER_DETAIL_PROMPTPAY_CATEGORY_FOOD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_REVIEW_CATEGORY_FOOD, PB3_TRANSFER_REVIEW_CATEGORY_FOOD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_PROMPTPAY_CITIZEN_REVIEW_TO_ACCOUNT_NUMBER, PB3_PROMPTPAY_CITIZEN_REVIEW_TO_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_TRANSFER_COMPLETE_CATEGORY_FOOD, PB3_TRANSFER_COMPLETE_CATEGORY_FOOD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_PROMPTPAY_CITIZEN_REVIEW_TO_ACCOUNT_NUMBER_XPATH, PB3_PROMPTPAY_CITIZEN_REVIEW_TO_ACCOUNT_NUMBER_XPATH);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_MENU, PB3_OTHER_TRANSFER_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_SELECT_BANK_MENU, PB3_OTHER_TRANSFER_SELECT_BANK_MENU);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_SELECT_BANK_TTB, PB3_OTHER_TRANSFER_SELECT_BANK_TTB);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_SELECT_BANK_SCB, PB3_OTHER_TRANSFER_SELECT_BANK_SCB);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_TO_ACCOUNT_TEXTFIELD, PB3_OTHER_TRANSFER_TO_ACCOUNT_TEXTFIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_OWN_ACCOUNT_NAME, PB3_OTHER_TRANSFER_OWN_ACCOUNT_NAME);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_OWN_ACCOUNT_NAME_TEXTFIELD, PB3_OTHER_TRANSFER_OWN_ACCOUNT_NAME_TEXTFIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_XPATH_TTB, PB3_OTHER_TRANSFER_XPATH_TTB);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_OTHER_ACCOUNT_NUMBER, PB3_OTHER_TRANSFER_OTHER_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_BANK_SCB, PB3_OTHER_TRANSFER_BANK_SCB);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_OTHER_BANK_ACCOUNT, PB3_OTHER_TRANSFER_OTHER_BANK_ACCOUNT);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_OWN_ACCOUNT_NUMBER, PB3_OTHER_TRANSFER_OWN_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_AMOUNT_TEXT_FIELD, PB3_OTHER_TRANSFER_AMOUNT_TEXT_FIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TRANSFER_AMOUNT_TEXT_FIELD_WITHOUT_DAILYLIMIT, PB3_OTHER_TRANSFER_AMOUNT_TEXT_FIELD_WITHOUT_DAILYLIMIT);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_O_SMALL, PB3_KEYPAD_O_SMALL);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_T_SMALL, PB3_KEYPAD_T_SMALL);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_E_SMALL, PB3_KEYPAD_E_SMALL);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEYPAD_D_SMALL, PB3_KEYPAD_D_SMALL);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_ENTER_DETAILS_TO_ACCOUNT_NUMBER, PB3_OTHER_ENTER_DETAILS_TO_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_BANK_ENTER_DETAILS_TO_ACCOUNT_NUMBER, PB3_OTHER_BANK_ENTER_DETAILS_TO_ACCOUNT_NUMBER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ONEHUNDRED_ONE, PB3_ONEHUNDRED_ONE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_OTHER_TTB_ACCOUNT_NUMBER_TEXTFIELD, PB3_OTHER_TTB_ACCOUNT_NUMBER_TEXTFIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_A_BUTTON, PB3_KEY_BOARD_A_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_B_BUTTON, PB3_KEY_BOARD_B_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_C_BUTTON, PB3_KEY_BOARD_C_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_D_BUTTON, PB3_KEY_BOARD_D_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_E_BUTTON, PB3_KEY_BOARD_E_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_F_BUTTON, PB3_KEY_BOARD_F_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_G_BUTTON, PB3_KEY_BOARD_G_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_H_BUTTON, PB3_KEY_BOARD_H_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_I_BUTTON, PB3_KEY_BOARD_I_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_J_BUTTON, PB3_KEY_BOARD_J_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_K_BUTTON, PB3_KEY_BOARD_K_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_L_BUTTON, PB3_KEY_BOARD_L_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_M_BUTTON, PB3_KEY_BOARD_M_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_N_BUTTON, PB3_KEY_BOARD_N_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_O_BUTTON, PB3_KEY_BOARD_O_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_P_BUTTON, PB3_KEY_BOARD_P_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_Q_BUTTON, PB3_KEY_BOARD_Q_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_R_BUTTON, PB3_KEY_BOARD_R_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_S_BUTTON, PB3_KEY_BOARD_S_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_T_BUTTON, PB3_KEY_BOARD_T_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_U_BUTTON, PB3_KEY_BOARD_U_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_V_BUTTON, PB3_KEY_BOARD_V_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_W_BUTTON, PB3_KEY_BOARD_W_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_X_BUTTON, PB3_KEY_BOARD_X_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_Y_BUTTON, PB3_KEY_BOARD_Y_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_KEY_BOARD_Z_BUTTON, PB3_KEY_BOARD_Z_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_BUTTON, PB3_SET_SCHEDULE_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_NAME_TEXTFIELD, PB3_SET_SCHEDULE_NAME_TEXTFIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SET_SCHEDULE_STARTDATE_TEXTFIELD, PB3_SET_SCHEDULE_STARTDATE_TEXTFIELD);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_ADD_SCHEDULE_BUTTON, PB3_ADD_SCHEDULE_BUTTON);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_REVIEW_TITLE_SCHEDULE, PB3_REVIEW_TITLE_SCHEDULE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_MONTHLY_NOTE, PB3_SCHEDULE_MONTHLY_NOTE);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_RADIO_MONTHLY, PB3_SCHEDULE_RADIO_MONTHLY);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_SCHEDULE_ERROR_AMOUNT_OF_TIME, PB3_SCHEDULE_ERROR_AMOUNT_OF_TIME);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_MESSAGE_ERROR_SCHEDULE_NAME_PLEASE_ENTER, PB3_MESSAGE_ERROR_SCHEDULE_NAME_PLEASE_ENTER);
        oneAppElementHashMap.put(OneAppElementKeys.PB3_MESSAGE_ERROR_SCHEDULE_NAME_MUST_BE_BETWEEN, PB3_MESSAGE_ERROR_SCHEDULE_NAME_MUST_BE_BETWEEN);
    }
}
